import 'package:flutter/material.dart';
import 'package:auto_size_text/auto_size_text.dart';

class Negotiationfeature extends StatefulWidget {
  const Negotiationfeature({Key? key}) : super(key: key);
  @override
  _Negotiationfeature createState() => _Negotiationfeature();
}

class _Negotiationfeature extends State<Negotiationfeature> {
  _Negotiationfeature();

  @override
  Widget build(BuildContext context) {
    return Material(
      color: Colors.white,
      child: Stack(children: [
        Positioned(
          left: 225.0,
          width: 111.0,
          top: 17.0,
          height: 14.0,
          child: LayoutBuilder(builder: (context, constraints) {
            return Container(/** This Symbol was not found **/);
          }),
        ),
        Positioned(
          left: 25.0,
          width: 311.0,
          top: 286.0,
          height: 258.0,
          child: Container(
            width: 311.000,
            height: 258.000,
            decoration: BoxDecoration(
              color: Color(0xff3b5080),
              borderRadius: BorderRadius.all(Radius.circular(10)),
            ),
          ),
        ),
        Positioned(
          left: MediaQuery.of(context).size.width * 0.294,
          width: MediaQuery.of(context).size.width * 0.211,
          top: MediaQuery.of(context).size.height * 0.134,
          height: MediaQuery.of(context).size.height * 0.037,
          child: Container(
              width: MediaQuery.of(context).size.width * 0.211,
              height: MediaQuery.of(context).size.height * 0.037,
              child: AutoSizeText(
                'John Doe',
                style: TextStyle(
                  fontFamily: 'Poppins',
                  fontSize: 16,
                  fontWeight: FontWeight.w500,
                  fontStyle: FontStyle.normal,
                  letterSpacing: 0,
                  color: Colors.white,
                ),
                textAlign: TextAlign.left,
              )),
        ),
        Positioned(
          left: MediaQuery.of(context).size.width * 0.103,
          width: MediaQuery.of(context).size.width * 0.803,
          top: MediaQuery.of(context).size.height * 0.541,
          height: MediaQuery.of(context).size.height * 0.269,
          child: Container(
              width: MediaQuery.of(context).size.width * 0.803,
              height: MediaQuery.of(context).size.height * 0.269,
              child: AutoSizeText(
                'Step 1: Select Delivery as your transportation option  Step 2:  Search and select a Destination and PickUp location  Step 3: Request a delivery Rider/Driver to start trip',
                style: TextStyle(
                  fontFamily: 'Poppins',
                  fontSize: 14,
                  fontWeight: FontWeight.w400,
                  fontStyle: FontStyle.normal,
                  letterSpacing: 0,
                  color: Colors.white,
                ),
                textAlign: TextAlign.left,
              )),
        ),
        Positioned(
          left: MediaQuery.of(context).size.width * 0.1,
          width: MediaQuery.of(context).size.width * 0.791,
          top: MediaQuery.of(context).size.height * 0.48,
          height: MediaQuery.of(context).size.height * 0.035,
          child: Container(
              width: MediaQuery.of(context).size.width * 0.791,
              height: MediaQuery.of(context).size.height * 0.035,
              child: AutoSizeText(
                '    Using the Delivery Feature',
                style: TextStyle(
                  fontFamily: 'Poppins',
                  fontSize: 18,
                  fontWeight: FontWeight.w700,
                  fontStyle: FontStyle.normal,
                  letterSpacing: 0,
                  color: Colors.white,
                ),
                textAlign: TextAlign.left,
              )),
        ),
        Positioned(
          left: MediaQuery.of(context).size.width * 0.072,
          width: MediaQuery.of(context).size.width * 0.136,
          top: MediaQuery.of(context).size.height * 0.492,
          height: MediaQuery.of(context).size.height * 0.037,
          child: Container(
              width: MediaQuery.of(context).size.width * 0.136,
              height: MediaQuery.of(context).size.height * 0.037,
              child: AutoSizeText(
                'About',
                style: TextStyle(
                  fontFamily: 'Poppins',
                  fontSize: 16,
                  fontWeight: FontWeight.w500,
                  fontStyle: FontStyle.normal,
                  letterSpacing: 0,
                  color: Colors.white,
                ),
                textAlign: TextAlign.left,
              )),
        ),
        Positioned(
          left: MediaQuery.of(context).size.width * 0.072,
          width: MediaQuery.of(context).size.width * 0.192,
          top: MediaQuery.of(context).size.height * 0.555,
          height: MediaQuery.of(context).size.height * 0.037,
          child: Container(
              width: MediaQuery.of(context).size.width * 0.192,
              height: MediaQuery.of(context).size.height * 0.037,
              child: AutoSizeText(
                'Sign Out',
                style: TextStyle(
                  fontFamily: 'Poppins',
                  fontSize: 16,
                  fontWeight: FontWeight.w500,
                  fontStyle: FontStyle.normal,
                  letterSpacing: 0,
                  color: Colors.white,
                ),
                textAlign: TextAlign.left,
              )),
        ),
        Positioned(
          left: MediaQuery.of(context).size.width * 0.3,
          width: MediaQuery.of(context).size.width * 0.183,
          top: MediaQuery.of(context).size.height * 0.173,
          height: MediaQuery.of(context).size.height * 0.023,
          child: Container(
              width: MediaQuery.of(context).size.width * 0.183,
              height: MediaQuery.of(context).size.height * 0.023,
              child: AutoSizeText(
                'Edit Profile ',
                style: TextStyle(
                  fontFamily: 'Poppins',
                  fontSize: 10,
                  fontWeight: FontWeight.w400,
                  fontStyle: FontStyle.normal,
                  letterSpacing: 0,
                  color: Colors.white,
                ),
                textAlign: TextAlign.left,
              )),
        ),
        Positioned(
          left: MediaQuery.of(context).size.width * 0.075,
          width: MediaQuery.of(context).size.width * 0.028,
          top: MediaQuery.of(context).size.height * 0.078,
          height: MediaQuery.of(context).size.height * 0.024,
          child: Image.asset(
            'assets/images/479_824.png',
            package: 'parabeac',
            width: MediaQuery.of(context).size.width * 0.028,
            height: MediaQuery.of(context).size.height * 0.024,
            fit: BoxFit.fill,
          ),
        ),
        Positioned(
          left: 32.0,
          width: 279.001,
          top: 58.0,
          height: 181.002,
          child: Stack(children: [
            Positioned(
              left: 0.005,
              width: 278.996,
              top: 0.015,
              height: 180.987,
              child: Image.asset(
                'assets/images/479_647.png',
                package: 'parabeac',
                width: 278.996,
                height: 180.987,
                fit: BoxFit.none,
              ),
            ),
            Positioned(
              left: 0,
              width: 279.0,
              top: 0,
              height: 181.0,
              child: Container(
                width: 279.000,
                height: 181.000,
                decoration: BoxDecoration(
                  borderRadius: BorderRadius.all(Radius.circular(0)),
                ),
              ),
            ),
            Positioned(
              left: 0.12,
              width: 278.825,
              top: 1.471,
              height: 170.74,
              child: Image.asset(
                'assets/images/479_648.png',
                package: 'parabeac',
                width: 278.825,
                height: 170.740,
                fit: BoxFit.none,
              ),
            ),
            Positioned(
              left: 0.005,
              width: 228.617,
              top: 125.642,
              height: 12.409,
              child: Image.asset(
                'assets/images/479_649.png',
                package: 'parabeac',
                width: 228.617,
                height: 12.409,
                fit: BoxFit.none,
              ),
            ),
            Positioned(
              left: 0.005,
              width: 228.617,
              top: 128.983,
              height: 9.068,
              child: Image.asset(
                'assets/images/479_650.png',
                package: 'parabeac',
                width: 228.617,
                height: 9.068,
                fit: BoxFit.none,
              ),
            ),
            Positioned(
              left: 116.905,
              width: 91.886,
              top: 41.252,
              height: 133.742,
              child: Image.asset(
                'assets/images/479_651.png',
                package: 'parabeac',
                width: 91.886,
                height: 133.742,
                fit: BoxFit.none,
              ),
            ),
            Positioned(
              left: 127.419,
              width: 50.856,
              top: 143.031,
              height: 24.889,
              child: Image.asset(
                'assets/images/479_652.png',
                package: 'parabeac',
                width: 50.856,
                height: 24.889,
                fit: BoxFit.none,
              ),
            ),
            Positioned(
              left: 127.419,
              width: 50.856,
              top: 143.031,
              height: 24.889,
              child: Image.asset(
                'assets/images/479_653.png',
                package: 'parabeac',
                width: 50.856,
                height: 24.889,
                fit: BoxFit.none,
              ),
            ),
            Positioned(
              left: 157.425,
              width: 10.561,
              top: 167.295,
              height: 5.984,
              child: Image.asset(
                'assets/images/479_654.png',
                package: 'parabeac',
                width: 10.561,
                height: 5.984,
                fit: BoxFit.none,
              ),
            ),
            Positioned(
              left: 157.425,
              width: 10.561,
              top: 167.295,
              height: 5.984,
              child: Image.asset(
                'assets/images/479_655.png',
                package: 'parabeac',
                width: 10.561,
                height: 5.984,
                fit: BoxFit.none,
              ),
            ),
            Positioned(
              left: 160.732,
              width: 7.17,
              top: 166.571,
              height: 5.618,
              child: Image.asset(
                'assets/images/479_656.png',
                package: 'parabeac',
                width: 7.170,
                height: 5.618,
                fit: BoxFit.none,
              ),
            ),
            Positioned(
              left: 160.732,
              width: 7.17,
              top: 166.571,
              height: 5.618,
              child: Image.asset(
                'assets/images/479_657.png',
                package: 'parabeac',
                width: 7.170,
                height: 5.618,
                fit: BoxFit.none,
              ),
            ),
            Positioned(
              left: 167.476,
              width: 34.017,
              top: 169.536,
              height: 5.59,
              child: Image.asset(
                'assets/images/479_658.png',
                package: 'parabeac',
                width: 34.017,
                height: 5.590,
                fit: BoxFit.none,
              ),
            ),
            Positioned(
              left: 169.769,
              width: 6.481,
              top: 170.776,
              height: 4.266,
              child: Image.asset(
                'assets/images/479_659.png',
                package: 'parabeac',
                width: 6.481,
                height: 4.266,
                fit: BoxFit.none,
              ),
            ),
            Positioned(
              left: 169.516,
              width: 6.5,
              top: 170.758,
              height: 4.281,
              child: Image.asset(
                'assets/images/479_660.png',
                package: 'parabeac',
                width: 6.500,
                height: 4.281,
                fit: BoxFit.none,
              ),
            ),
            Positioned(
              left: 169.516,
              width: 6.5,
              top: 170.758,
              height: 4.281,
              child: Image.asset(
                'assets/images/479_661.png',
                package: 'parabeac',
                width: 6.500,
                height: 4.281,
                fit: BoxFit.none,
              ),
            ),
            Positioned(
              left: 167.532,
              width: 33.962,
              top: 169.536,
              height: 3.061,
              child: Image.asset(
                'assets/images/479_662.png',
                package: 'parabeac',
                width: 33.962,
                height: 3.061,
                fit: BoxFit.none,
              ),
            ),
            Positioned(
              left: 166.503,
              width: 37.073,
              top: 166.861,
              height: 5.198,
              child: Image.asset(
                'assets/images/479_663.png',
                package: 'parabeac',
                width: 37.073,
                height: 5.198,
                fit: BoxFit.none,
              ),
            ),
            Positioned(
              left: 165.379,
              width: 40.69,
              top: 162.719,
              height: 6.509,
              child: Image.asset(
                'assets/images/479_664.png',
                package: 'parabeac',
                width: 40.690,
                height: 6.509,
                fit: BoxFit.none,
              ),
            ),
            Positioned(
              left: 125.294,
              width: 82.163,
              top: 145.56,
              height: 25.15,
              child: Image.asset(
                'assets/images/479_665.png',
                package: 'parabeac',
                width: 82.163,
                height: 25.150,
                fit: BoxFit.none,
              ),
            ),
            Positioned(
              left: 117.332,
              width: 33.608,
              top: 119.524,
              height: 11.872,
              child: Image.asset(
                'assets/images/479_666.png',
                package: 'parabeac',
                width: 33.608,
                height: 11.872,
                fit: BoxFit.none,
              ),
            ),
            Positioned(
              left: 140.997,
              width: 22.938,
              top: 104.129,
              height: 27.557,
              child: Image.asset(
                'assets/images/479_667.png',
                package: 'parabeac',
                width: 22.938,
                height: 27.557,
                fit: BoxFit.none,
              ),
            ),
            Positioned(
              left: 140.997,
              width: 22.938,
              top: 104.22,
              height: 27.56,
              child: Image.asset(
                'assets/images/479_668.png',
                package: 'parabeac',
                width: 22.938,
                height: 27.560,
                fit: BoxFit.none,
              ),
            ),
            Positioned(
              left: 141.501,
              width: 14.483,
              top: 120.31,
              height: 11.388,
              child: Image.asset(
                'assets/images/479_669.png',
                package: 'parabeac',
                width: 14.483,
                height: 11.388,
                fit: BoxFit.none,
              ),
            ),
            Positioned(
              left: 140.858,
              width: 10.082,
              top: 121.978,
              height: 9.37,
              child: Image.asset(
                'assets/images/479_670.png',
                package: 'parabeac',
                width: 10.082,
                height: 9.370,
                fit: BoxFit.none,
              ),
            ),
            Positioned(
              left: 140.997,
              width: 14.482,
              top: 120.31,
              height: 11.388,
              child: Image.asset(
                'assets/images/479_671.png',
                package: 'parabeac',
                width: 14.482,
                height: 11.388,
                fit: BoxFit.none,
              ),
            ),
            Positioned(
              left: 140.997,
              width: 14.482,
              top: 120.489,
              height: 11.39,
              child: Image.asset(
                'assets/images/479_672.png',
                package: 'parabeac',
                width: 14.482,
                height: 11.390,
                fit: BoxFit.none,
              ),
            ),
            Positioned(
              left: 151.959,
              width: 19.314,
              top: 61.146,
              height: 27.91,
              child: Image.asset(
                'assets/images/479_673.png',
                package: 'parabeac',
                width: 19.314,
                height: 27.910,
                fit: BoxFit.none,
              ),
            ),
            Positioned(
              left: 151.954,
              width: 10.613,
              top: 61.146,
              height: 11.315,
              child: Image.asset(
                'assets/images/479_674.png',
                package: 'parabeac',
                width: 10.613,
                height: 11.315,
                fit: BoxFit.none,
              ),
            ),
            Positioned(
              left: 138.923,
              width: 24.125,
              top: 46.707,
              height: 25.51,
              child: Image.asset(
                'assets/images/479_675.png',
                package: 'parabeac',
                width: 24.125,
                height: 25.510,
                fit: BoxFit.none,
              ),
            ),
            Positioned(
              left: 160.929,
              width: 46.529,
              top: 145.552,
              height: 20.017,
              child: Image.asset(
                'assets/images/479_676.png',
                package: 'parabeac',
                width: 46.529,
                height: 20.017,
                fit: BoxFit.none,
              ),
            ),
            Positioned(
              left: 152.129,
              width: 56.229,
              top: 66.787,
              height: 98.13,
              child: Image.asset(
                'assets/images/479_677.png',
                package: 'parabeac',
                width: 56.229,
                height: 98.130,
                fit: BoxFit.none,
              ),
            ),
            Positioned(
              left: 139.716,
              width: 29.45,
              top: 132.771,
              height: 24.698,
              child: Image.asset(
                'assets/images/479_678.png',
                package: 'parabeac',
                width: 29.450,
                height: 24.698,
                fit: BoxFit.none,
              ),
            ),
            Positioned(
              left: 184.938,
              width: 6.525,
              top: 90.207,
              height: 2.983,
              child: Image.asset(
                'assets/images/479_679.png',
                package: 'parabeac',
                width: 6.525,
                height: 2.983,
                fit: BoxFit.none,
              ),
            ),
            Positioned(
              left: 175.865,
              width: 25.265,
              top: 132.146,
              height: 9.237,
              child: Image.asset(
                'assets/images/479_680.png',
                package: 'parabeac',
                width: 25.265,
                height: 9.237,
                fit: BoxFit.none,
              ),
            ),
            Positioned(
              left: 139.363,
              width: 23.685,
              top: 46.702,
              height: 19.134,
              child: Image.asset(
                'assets/images/479_681.png',
                package: 'parabeac',
                width: 23.685,
                height: 19.134,
                fit: BoxFit.none,
              ),
            ),
            Positioned(
              left: 132.162,
              width: 35.164,
              top: 42.296,
              height: 24.746,
              child: Image.asset(
                'assets/images/479_682.png',
                package: 'parabeac',
                width: 35.164,
                height: 24.746,
                fit: BoxFit.none,
              ),
            ),
            Positioned(
              left: 155.924,
              width: 13.242,
              top: 132.771,
              height: 5.925,
              child: Image.asset(
                'assets/images/479_683.png',
                package: 'parabeac',
                width: 13.242,
                height: 5.925,
                fit: BoxFit.none,
              ),
            ),
            Positioned(
              left: 154.784,
              width: 29.445,
              top: 69.139,
              height: 69.606,
              child: Image.asset(
                'assets/images/479_684.png',
                package: 'parabeac',
                width: 29.445,
                height: 69.606,
                fit: BoxFit.none,
              ),
            ),
            Positioned(
              left: 157.384,
              width: 25.838,
              top: 68.598,
              height: 69.364,
              child: Image.asset(
                'assets/images/479_685.png',
                package: 'parabeac',
                width: 25.838,
                height: 69.364,
                fit: BoxFit.none,
              ),
            ),
            Positioned(
              left: 154.282,
              width: 29.436,
              top: 68.598,
              height: 69.611,
              child: Image.asset(
                'assets/images/479_686.png',
                package: 'parabeac',
                width: 29.436,
                height: 69.611,
                fit: BoxFit.none,
              ),
            ),
            Positioned(
              left: 154.53,
              width: 11.971,
              top: 129.463,
              height: 8.479,
              child: Image.asset(
                'assets/images/479_687.png',
                package: 'parabeac',
                width: 11.971,
                height: 8.479,
                fit: BoxFit.none,
              ),
            ),
            Positioned(
              left: 154.277,
              width: 11.971,
              top: 129.73,
              height: 8.479,
              child: Image.asset(
                'assets/images/479_688.png',
                package: 'parabeac',
                width: 11.971,
                height: 8.479,
                fit: BoxFit.none,
              ),
            ),
            Positioned(
              left: 132.183,
              width: 35.147,
              top: 53.984,
              height: 13.059,
              child: Image.asset(
                'assets/images/479_689.png',
                package: 'parabeac',
                width: 35.147,
                height: 13.059,
                fit: BoxFit.none,
              ),
            ),
            Positioned(
              left: 115.354,
              width: 4.472,
              top: 166.838,
              height: 4.37,
              child: Image.asset(
                'assets/images/479_692.png',
                package: 'parabeac',
                width: 4.472,
                height: 4.370,
                fit: BoxFit.none,
              ),
            ),
            Positioned(
              left: 66.842,
              width: 54.518,
              top: 46.694,
              height: 111.507,
              child: Image.asset(
                'assets/images/479_693.png',
                package: 'parabeac',
                width: 54.518,
                height: 111.507,
                fit: BoxFit.none,
              ),
            ),
            Positioned(
              left: 84.148,
              width: 30.533,
              top: 143.114,
              height: 14.894,
              child: Image.asset(
                'assets/images/479_694.png',
                package: 'parabeac',
                width: 30.533,
                height: 14.894,
                fit: BoxFit.none,
              ),
            ),
            Positioned(
              left: 84.148,
              width: 30.533,
              top: 143.114,
              height: 14.894,
              child: Image.asset(
                'assets/images/479_695.png',
                package: 'parabeac',
                width: 30.533,
                height: 14.894,
                fit: BoxFit.none,
              ),
            ),
            Positioned(
              left: 70.812,
              width: 12.877,
              top: 122.156,
              height: 8.656,
              child: Image.asset(
                'assets/images/479_696.png',
                package: 'parabeac',
                width: 12.877,
                height: 8.656,
                fit: BoxFit.none,
              ),
            ),
            Positioned(
              left: 60.278,
              width: 14.508,
              top: 119.124,
              height: 11.323,
              child: Image.asset(
                'assets/images/479_697.png',
                package: 'parabeac',
                width: 14.508,
                height: 11.323,
                fit: BoxFit.none,
              ),
            ),
            Positioned(
              left: 60.785,
              width: 14.506,
              top: 119.211,
              height: 11.332,
              child: Image.asset(
                'assets/images/479_698.png',
                package: 'parabeac',
                width: 14.506,
                height: 11.332,
                fit: BoxFit.none,
              ),
            ),
            Positioned(
              left: 48.2,
              width: 20.596,
              top: 53.483,
              height: 23.456,
              child: Image.asset(
                'assets/images/479_699.png',
                package: 'parabeac',
                width: 20.596,
                height: 23.456,
                fit: BoxFit.none,
              ),
            ),
            Positioned(
              left: 55.672,
              width: 36.994,
              top: 169.157,
              height: 6.347,
              child: Image.asset(
                'assets/images/479_700.png',
                package: 'parabeac',
                width: 36.994,
                height: 6.347,
                fit: BoxFit.none,
              ),
            ),
            Positioned(
              left: 49.991,
              width: 7.504,
              top: 168.174,
              height: 6.863,
              child: Image.asset(
                'assets/images/479_701.png',
                package: 'parabeac',
                width: 7.504,
                height: 6.863,
                fit: BoxFit.none,
              ),
            ),
            Positioned(
              left: 49.734,
              width: 7.509,
              top: 168.174,
              height: 6.957,
              child: Image.asset(
                'assets/images/479_702.png',
                package: 'parabeac',
                width: 7.509,
                height: 6.957,
                fit: BoxFit.none,
              ),
            ),
            Positioned(
              left: 90.472,
              width: 7.17,
              top: 169.513,
              height: 5.996,
              child: Image.asset(
                'assets/images/479_703.png',
                package: 'parabeac',
                width: 7.170,
                height: 5.996,
                fit: BoxFit.none,
              ),
            ),
            Positioned(
              left: 90.727,
              width: 7.168,
              top: 169.513,
              height: 6.065,
              child: Image.asset(
                'assets/images/479_704.png',
                package: 'parabeac',
                width: 7.168,
                height: 6.065,
                fit: BoxFit.none,
              ),
            ),
            Positioned(
              left: 49.734,
              width: 7.509,
              top: 168.174,
              height: 6.957,
              child: Image.asset(
                'assets/images/479_705.png',
                package: 'parabeac',
                width: 7.509,
                height: 6.957,
                fit: BoxFit.none,
              ),
            ),
            Positioned(
              left: 90.727,
              width: 7.168,
              top: 169.513,
              height: 6.065,
              child: Image.asset(
                'assets/images/479_706.png',
                package: 'parabeac',
                width: 7.168,
                height: 6.065,
                fit: BoxFit.none,
              ),
            ),
            Positioned(
              left: 55.563,
              width: 12.695,
              top: 53.476,
              height: 14.96,
              child: Image.asset(
                'assets/images/479_707.png',
                package: 'parabeac',
                width: 12.695,
                height: 14.960,
                fit: BoxFit.none,
              ),
            ),
            Positioned(
              left: 55.078,
              width: 26.792,
              top: 39.66,
              height: 28.33,
              child: Image.asset(
                'assets/images/479_708.png',
                package: 'parabeac',
                width: 26.792,
                height: 28.330,
                fit: BoxFit.none,
              ),
            ),
            Positioned(
              left: 55.05,
              width: 26.255,
              top: 39.666,
              height: 21.242,
              child: Image.asset(
                'assets/images/479_709.png',
                package: 'parabeac',
                width: 26.255,
                height: 21.242,
                fit: BoxFit.none,
              ),
            ),
            Positioned(
              left: 51.082,
              width: 33.686,
              top: 35.8,
              height: 26.654,
              child: Image.asset(
                'assets/images/479_710.png',
                package: 'parabeac',
                width: 33.686,
                height: 26.654,
                fit: BoxFit.none,
              ),
            ),
            Positioned(
              left: 63.3,
              width: 2.882,
              top: 122.781,
              height: 1.76,
              child: Image.asset(
                'assets/images/479_711.png',
                package: 'parabeac',
                width: 2.882,
                height: 1.760,
                fit: BoxFit.none,
              ),
            ),
            Positioned(
              left: 25.451,
              width: 97.684,
              top: 137.156,
              height: 40.283,
              child: Image.asset(
                'assets/images/479_712.png',
                package: 'parabeac',
                width: 97.684,
                height: 40.283,
                fit: BoxFit.none,
              ),
            ),
            Positioned(
              left: 50.941,
              width: 7.823,
              top: 147.668,
              height: 10.529,
              child: Image.asset(
                'assets/images/479_713.png',
                package: 'parabeac',
                width: 7.823,
                height: 10.529,
                fit: BoxFit.none,
              ),
            ),
            Positioned(
              left: 64.676,
              width: 4.711,
              top: 152.299,
              height: 5.709,
              child: Image.asset(
                'assets/images/479_714.png',
                package: 'parabeac',
                width: 4.711,
                height: 5.709,
                fit: BoxFit.none,
              ),
            ),
            Positioned(
              left: 113.249,
              width: 4.806,
              top: 161.754,
              height: 6.86,
              child: Image.asset(
                'assets/images/479_715.png',
                package: 'parabeac',
                width: 4.806,
                height: 6.860,
                fit: BoxFit.none,
              ),
            ),
            Positioned(
              left: 50.296,
              width: 47.598,
              top: 168.174,
              height: 3.227,
              child: Image.asset(
                'assets/images/479_716.png',
                package: 'parabeac',
                width: 47.598,
                height: 3.227,
                fit: BoxFit.none,
              ),
            ),
            Positioned(
              left: 46.02,
              width: 55.924,
              top: 166.302,
              height: 4.597,
              child: Image.asset(
                'assets/images/479_717.png',
                package: 'parabeac',
                width: 55.924,
                height: 4.597,
                fit: BoxFit.none,
              ),
            ),
            Positioned(
              left: 25.434,
              width: 41.407,
              top: 137.146,
              height: 19.663,
              child: Image.asset(
                'assets/images/479_718.png',
                package: 'parabeac',
                width: 41.407,
                height: 19.663,
                fit: BoxFit.none,
              ),
            ),
            Positioned(
              left: 20.559,
              width: 47.226,
              top: 64.867,
              height: 91.0,
              child: Image.asset(
                'assets/images/479_719.png',
                package: 'parabeac',
                width: 47.226,
                height: 91.000,
                fit: BoxFit.none,
              ),
            ),
            Positioned(
              left: 48.259,
              width: 13.757,
              top: 127.865,
              height: 4.093,
              child: Image.asset(
                'assets/images/479_720.png',
                package: 'parabeac',
                width: 13.757,
                height: 4.093,
                fit: BoxFit.none,
              ),
            ),
            Positioned(
              left: 48.386,
              width: 12.651,
              top: 116.538,
              height: 10.346,
              child: Image.asset(
                'assets/images/479_721.png',
                package: 'parabeac',
                width: 12.651,
                height: 10.346,
                fit: BoxFit.none,
              ),
            ),
            Positioned(
              left: 54.881,
              width: 6.814,
              top: 110.826,
              height: 10.184,
              child: Image.asset(
                'assets/images/479_722.png',
                package: 'parabeac',
                width: 6.814,
                height: 10.184,
                fit: BoxFit.none,
              ),
            ),
            Positioned(
              left: 42.062,
              width: 11.069,
              top: 86.216,
              height: 14.586,
              child: Image.asset(
                'assets/images/479_723.png',
                package: 'parabeac',
                width: 11.069,
                height: 14.586,
                fit: BoxFit.none,
              ),
            ),
            Positioned(
              left: 28.278,
              width: 20.616,
              top: 111.812,
              height: 24.263,
              child: Image.asset(
                'assets/images/479_724.png',
                package: 'parabeac',
                width: 20.616,
                height: 24.263,
                fit: BoxFit.none,
              ),
            ),
            Positioned(
              left: 106.079,
              width: 14.135,
              top: 142.84,
              height: 11.871,
              child: Image.asset(
                'assets/images/479_725.png',
                package: 'parabeac',
                width: 14.135,
                height: 11.871,
                fit: BoxFit.none,
              ),
            ),
            Positioned(
              left: 52.118,
              width: 15.667,
              top: 69.249,
              height: 44.626,
              child: Image.asset(
                'assets/images/479_726.png',
                package: 'parabeac',
                width: 15.667,
                height: 44.626,
                fit: BoxFit.none,
              ),
            ),
            Positioned(
              left: 95.915,
              width: 11.93,
              top: 145.538,
              height: 5.953,
              child: Image.asset(
                'assets/images/479_727.png',
                package: 'parabeac',
                width: 11.930,
                height: 5.953,
                fit: BoxFit.none,
              ),
            ),
            Positioned(
              left: 106.132,
              width: 3.635,
              top: 142.84,
              height: 8.13,
              child: Image.asset(
                'assets/images/479_728.png',
                package: 'parabeac',
                width: 3.635,
                height: 8.130,
                fit: BoxFit.none,
              ),
            ),
            Positioned(
              left: 52.892,
              width: 56.374,
              top: 68.711,
              height: 82.259,
              child: Image.asset(
                'assets/images/479_729.png',
                package: 'parabeac',
                width: 56.374,
                height: 82.259,
                fit: BoxFit.none,
              ),
            ),
            Positioned(
              left: 75.546,
              width: 6.643,
              top: 109.168,
              height: 1.774,
              child: Image.asset(
                'assets/images/479_730.png',
                package: 'parabeac',
                width: 6.643,
                height: 1.774,
                fit: BoxFit.none,
              ),
            ),
            Positioned(
              left: 74.363,
              width: 5.37,
              top: 119.999,
              height: 1.451,
              child: Image.asset(
                'assets/images/479_731.png',
                package: 'parabeac',
                width: 5.370,
                height: 1.451,
                fit: BoxFit.none,
              ),
            ),
            Positioned(
              left: 61.205,
              width: 11.053,
              top: 78.723,
              height: 7.76,
              child: Image.asset(
                'assets/images/479_732.png',
                package: 'parabeac',
                width: 11.053,
                height: 7.760,
                fit: BoxFit.none,
              ),
            ),
            Positioned(
              left: 51.077,
              width: 33.671,
              top: 44.032,
              height: 18.237,
              child: Image.asset(
                'assets/images/479_733.png',
                package: 'parabeac',
                width: 33.671,
                height: 18.237,
                fit: BoxFit.none,
              ),
            ),
            Positioned(
              left: 5.702,
              width: 9.54,
              top: 110.748,
              height: 10.488,
              child: Image.asset(
                'assets/images/479_738.png',
                package: 'parabeac',
                width: 9.540,
                height: 10.488,
                fit: BoxFit.none,
              ),
            ),
            Positioned(
              left: 5.702,
              width: 9.54,
              top: 110.748,
              height: 10.488,
              child: Image.asset(
                'assets/images/479_739.png',
                package: 'parabeac',
                width: 9.540,
                height: 10.488,
                fit: BoxFit.none,
              ),
            ),
            Positioned(
              left: 5.896,
              width: 1.851,
              top: 111.316,
              height: 2.516,
              child: Image.asset(
                'assets/images/479_740.png',
                package: 'parabeac',
                width: 1.851,
                height: 2.516,
                fit: BoxFit.none,
              ),
            ),
            Positioned(
              left: 8.087,
              width: 0.85,
              top: 110.749,
              height: 1.77,
              child: Image.asset(
                'assets/images/479_741.png',
                package: 'parabeac',
                width: 0.850,
                height: 1.770,
                fit: BoxFit.none,
              ),
            ),
            Positioned(
              left: 12.12,
              width: 1.035,
              top: 110.844,
              height: 2.074,
              child: Image.asset(
                'assets/images/479_742.png',
                package: 'parabeac',
                width: 1.035,
                height: 2.074,
                fit: BoxFit.none,
              ),
            ),
            Positioned(
              left: 13.59,
              width: 1.837,
              top: 111.462,
              height: 2.159,
              child: Image.asset(
                'assets/images/479_743.png',
                package: 'parabeac',
                width: 1.837,
                height: 2.159,
                fit: BoxFit.none,
              ),
            ),
            Positioned(
              left: 6.935,
              width: 0.812,
              top: 112.325,
              height: 1.507,
              child: Image.asset(
                'assets/images/479_744.png',
                package: 'parabeac',
                width: 0.812,
                height: 1.507,
                fit: BoxFit.none,
              ),
            ),
            Positioned(
              left: 8.093,
              width: 0.416,
              top: 111.931,
              height: 0.587,
              child: Image.asset(
                'assets/images/479_745.png',
                package: 'parabeac',
                width: 0.416,
                height: 0.587,
                fit: BoxFit.none,
              ),
            ),
            Positioned(
              left: 6.914,
              width: 3.365,
              top: 112.133,
              height: 4.791,
              child: Image.asset(
                'assets/images/479_746.png',
                package: 'parabeac',
                width: 3.365,
                height: 4.791,
                fit: BoxFit.none,
              ),
            ),
            Positioned(
              left: 12.66,
              width: 0.493,
              top: 112.257,
              height: 0.661,
              child: Image.asset(
                'assets/images/479_747.png',
                package: 'parabeac',
                width: 0.493,
                height: 0.661,
                fit: BoxFit.none,
              ),
            ),
            Positioned(
              left: 13.59,
              width: 0.747,
              top: 112.374,
              height: 1.242,
              child: Image.asset(
                'assets/images/479_748.png',
                package: 'parabeac',
                width: 0.747,
                height: 1.242,
                fit: BoxFit.none,
              ),
            ),
            Positioned(
              left: 10.311,
              width: 4.085,
              top: 112.453,
              height: 5.271,
              child: Image.asset(
                'assets/images/479_749.png',
                package: 'parabeac',
                width: 4.085,
                height: 5.271,
                fit: BoxFit.none,
              ),
            ),
            Positioned(
              left: 6.32,
              width: 5.738,
              top: 125.517,
              height: 1.596,
              child: Image.asset(
                'assets/images/479_750.png',
                package: 'parabeac',
                width: 5.738,
                height: 1.596,
                fit: BoxFit.none,
              ),
            ),
            Positioned(
              left: 5.407,
              width: 7.499,
              top: 120.331,
              height: 5.569,
              child: Image.asset(
                'assets/images/479_751.png',
                package: 'parabeac',
                width: 7.499,
                height: 5.569,
                fit: BoxFit.none,
              ),
            ),
            Positioned(
              left: 6.32,
              width: 5.738,
              top: 125.517,
              height: 1.596,
              child: Image.asset(
                'assets/images/479_752.png',
                package: 'parabeac',
                width: 5.738,
                height: 1.596,
                fit: BoxFit.none,
              ),
            ),
            Positioned(
              left: 5.407,
              width: 7.499,
              top: 120.331,
              height: 5.569,
              child: Image.asset(
                'assets/images/479_753.png',
                package: 'parabeac',
                width: 7.499,
                height: 5.569,
                fit: BoxFit.none,
              ),
            ),
            Positioned(
              left: 6.697,
              width: 5.738,
              top: 125.517,
              height: 1.596,
              child: Image.asset(
                'assets/images/479_754.png',
                package: 'parabeac',
                width: 5.738,
                height: 1.596,
                fit: BoxFit.none,
              ),
            ),
            Positioned(
              left: 8.903,
              width: 1.377,
              top: 115.705,
              height: 1.22,
              child: Image.asset(
                'assets/images/479_755.png',
                package: 'parabeac',
                width: 1.377,
                height: 1.220,
                fit: BoxFit.none,
              ),
            ),
            Positioned(
              left: 10.311,
              width: 1.802,
              top: 116.06,
              height: 1.664,
              child: Image.asset(
                'assets/images/479_756.png',
                package: 'parabeac',
                width: 1.802,
                height: 1.664,
                fit: BoxFit.none,
              ),
            ),
            Positioned(
              left: 7.23,
              width: 4.885,
              top: 115.872,
              height: 5.357,
              child: Image.asset(
                'assets/images/479_757.png',
                package: 'parabeac',
                width: 4.885,
                height: 5.357,
                fit: BoxFit.none,
              ),
            ),
            Positioned(
              left: 7.888,
              width: 0.38,
              top: 113.466,
              height: 0.401,
              child: Image.asset(
                'assets/images/479_758.png',
                package: 'parabeac',
                width: 0.380,
                height: 0.401,
                fit: BoxFit.none,
              ),
            ),
            Positioned(
              left: 7.874,
              width: 0.38,
              top: 114.396,
              height: 0.401,
              child: Image.asset(
                'assets/images/479_759.png',
                package: 'parabeac',
                width: 0.380,
                height: 0.401,
                fit: BoxFit.none,
              ),
            ),
            Positioned(
              left: 13.343,
              width: 0.38,
              top: 113.649,
              height: 0.401,
              child: Image.asset(
                'assets/images/479_760.png',
                package: 'parabeac',
                width: 0.380,
                height: 0.401,
                fit: BoxFit.none,
              ),
            ),
            Positioned(
              left: 8.943,
              width: 0.38,
              top: 118.418,
              height: 0.401,
              child: Image.asset(
                'assets/images/479_761.png',
                package: 'parabeac',
                width: 0.380,
                height: 0.401,
                fit: BoxFit.none,
              ),
            ),
            Positioned(
              left: 12.951,
              width: 0.38,
              top: 115.194,
              height: 0.401,
              child: Image.asset(
                'assets/images/479_762.png',
                package: 'parabeac',
                width: 0.380,
                height: 0.401,
                fit: BoxFit.none,
              ),
            ),
            Positioned(
              left: 11.003,
              width: 0.38,
              top: 117.254,
              height: 0.401,
              child: Image.asset(
                'assets/images/479_763.png',
                package: 'parabeac',
                width: 0.380,
                height: 0.401,
                fit: BoxFit.none,
              ),
            ),
            Positioned(
              left: 8.532,
              width: 0.38,
              top: 113.865,
              height: 0.401,
              child: Image.asset(
                'assets/images/479_764.png',
                package: 'parabeac',
                width: 0.380,
                height: 0.401,
                fit: BoxFit.none,
              ),
            ),
            Positioned(
              left: 12.824,
              width: 0.38,
              top: 114.246,
              height: 0.401,
              child: Image.asset(
                'assets/images/479_765.png',
                package: 'parabeac',
                width: 0.380,
                height: 0.401,
                fit: BoxFit.none,
              ),
            ),
            Positioned(
              left: 12.18,
              width: 0.38,
              top: 115.791,
              height: 0.401,
              child: Image.asset(
                'assets/images/479_766.png',
                package: 'parabeac',
                width: 0.380,
                height: 0.401,
                fit: BoxFit.none,
              ),
            ),
            Positioned(
              left: 10.2,
              width: 0.38,
              top: 118.268,
              height: 0.401,
              child: Image.asset(
                'assets/images/479_767.png',
                package: 'parabeac',
                width: 0.380,
                height: 0.401,
                fit: BoxFit.none,
              ),
            ),
            Positioned(
              left: 9.792,
              width: 0.38,
              top: 117.287,
              height: 0.401,
              child: Image.asset(
                'assets/images/479_768.png',
                package: 'parabeac',
                width: 0.380,
                height: 0.401,
                fit: BoxFit.none,
              ),
            ),
            Positioned(
              left: 8.816,
              width: 0.38,
              top: 115.077,
              height: 0.401,
              child: Image.asset(
                'assets/images/479_769.png',
                package: 'parabeac',
                width: 0.380,
                height: 0.401,
                fit: BoxFit.none,
              ),
            ),
            Positioned(
              left: 6.697,
              width: 5.738,
              top: 125.517,
              height: 0.582,
              child: Image.asset(
                'assets/images/479_770.png',
                package: 'parabeac',
                width: 5.738,
                height: 0.582,
                fit: BoxFit.none,
              ),
            ),
            Positioned(
              left: 5.784,
              width: 7.499,
              top: 120.331,
              height: 5.569,
              child: Image.asset(
                'assets/images/479_771.png',
                package: 'parabeac',
                width: 7.499,
                height: 5.569,
                fit: BoxFit.none,
              ),
            ),
            Positioned(
              left: 10.452,
              width: 0.38,
              top: 119.165,
              height: 0.401,
              child: Image.asset(
                'assets/images/479_772.png',
                package: 'parabeac',
                width: 0.380,
                height: 0.401,
                fit: BoxFit.none,
              ),
            ),
            Positioned(
              left: 9.321,
              width: 0.38,
              top: 119.417,
              height: 0.401,
              child: Image.asset(
                'assets/images/479_773.png',
                package: 'parabeac',
                width: 0.380,
                height: 0.401,
                fit: BoxFit.none,
              ),
            ),
            Positioned(
              left: 232.212,
              width: 6.843,
              top: 86.724,
              height: 5.242,
              child: Image.asset(
                'assets/images/479_774.png',
                package: 'parabeac',
                width: 6.843,
                height: 5.242,
                fit: BoxFit.none,
              ),
            ),
            Positioned(
              left: 231.435,
              width: 7.043,
              top: 81.003,
              height: 5.094,
              child: Image.asset(
                'assets/images/479_775.png',
                package: 'parabeac',
                width: 7.043,
                height: 5.094,
                fit: BoxFit.none,
              ),
            ),
            Positioned(
              left: 231.212,
              width: 6.802,
              top: 74.426,
              height: 6.397,
              child: Image.asset(
                'assets/images/479_776.png',
                package: 'parabeac',
                width: 6.802,
                height: 6.397,
                fit: BoxFit.none,
              ),
            ),
            Positioned(
              left: 231.282,
              width: 6.394,
              top: 68.161,
              height: 7.262,
              child: Image.asset(
                'assets/images/479_777.png',
                package: 'parabeac',
                width: 6.394,
                height: 7.262,
                fit: BoxFit.none,
              ),
            ),
            Positioned(
              left: 231.712,
              width: 6.271,
              top: 62.405,
              height: 7.21,
              child: Image.asset(
                'assets/images/479_778.png',
                package: 'parabeac',
                width: 6.271,
                height: 7.210,
                fit: BoxFit.none,
              ),
            ),
            Positioned(
              left: 232.315,
              width: 5.478,
              top: 56.586,
              height: 6.639,
              child: Image.asset(
                'assets/images/479_779.png',
                package: 'parabeac',
                width: 5.478,
                height: 6.639,
                fit: BoxFit.none,
              ),
            ),
            Positioned(
              left: 232.824,
              width: 4.681,
              top: 50.086,
              height: 7.223,
              child: Image.asset(
                'assets/images/479_780.png',
                package: 'parabeac',
                width: 4.681,
                height: 7.223,
                fit: BoxFit.none,
              ),
            ),
            Positioned(
              left: 233.038,
              width: 4.191,
              top: 43.988,
              height: 7.007,
              child: Image.asset(
                'assets/images/479_781.png',
                package: 'parabeac',
                width: 4.191,
                height: 7.007,
                fit: BoxFit.none,
              ),
            ),
            Positioned(
              left: 233.033,
              width: 1.783,
              top: 35.411,
              height: 11.195,
              child: Image.asset(
                'assets/images/479_782.png',
                package: 'parabeac',
                width: 1.783,
                height: 11.195,
                fit: BoxFit.none,
              ),
            ),
            Positioned(
              left: 230.061,
              width: 2.9,
              top: 27.367,
              height: 10.892,
              child: Image.asset(
                'assets/images/479_783.png',
                package: 'parabeac',
                width: 2.900,
                height: 10.892,
                fit: BoxFit.none,
              ),
            ),
            Positioned(
              left: 225.69,
              width: 6.262,
              top: 95.108,
              height: 3.568,
              child: Image.asset(
                'assets/images/479_784.png',
                package: 'parabeac',
                width: 6.262,
                height: 3.568,
                fit: BoxFit.none,
              ),
            ),
            Positioned(
              left: 224.621,
              width: 7.689,
              top: 88.502,
              height: 4.155,
              child: Image.asset(
                'assets/images/479_785.png',
                package: 'parabeac',
                width: 7.689,
                height: 4.155,
                fit: BoxFit.none,
              ),
            ),
            Positioned(
              left: 224.047,
              width: 7.67,
              top: 82.296,
              height: 4.259,
              child: Image.asset(
                'assets/images/479_786.png',
                package: 'parabeac',
                width: 7.670,
                height: 4.259,
                fit: BoxFit.none,
              ),
            ),
            Positioned(
              left: 225.135,
              width: 6.538,
              top: 73.979,
              height: 6.728,
              child: Image.asset(
                'assets/images/479_787.png',
                package: 'parabeac',
                width: 6.538,
                height: 6.728,
                fit: BoxFit.none,
              ),
            ),
            Positioned(
              left: 225.818,
              width: 5.618,
              top: 67.456,
              height: 7.955,
              child: Image.asset(
                'assets/images/479_788.png',
                package: 'parabeac',
                width: 5.618,
                height: 7.955,
                fit: BoxFit.none,
              ),
            ),
            Positioned(
              left: 226.248,
              width: 6.007,
              top: 61.845,
              height: 7.454,
              child: Image.asset(
                'assets/images/479_789.png',
                package: 'parabeac',
                width: 6.007,
                height: 7.454,
                fit: BoxFit.none,
              ),
            ),
            Positioned(
              left: 228.8,
              width: 3.893,
              top: 55.206,
              height: 7.904,
              child: Image.asset(
                'assets/images/479_790.png',
                package: 'parabeac',
                width: 3.893,
                height: 7.904,
                fit: BoxFit.none,
              ),
            ),
            Positioned(
              left: 228.708,
              width: 4.241,
              top: 49.652,
              height: 7.531,
              child: Image.asset(
                'assets/images/479_791.png',
                package: 'parabeac',
                width: 4.241,
                height: 7.531,
                fit: BoxFit.none,
              ),
            ),
            Positioned(
              left: 230.265,
              width: 3.186,
              top: 43.75,
              height: 7.64,
              child: Image.asset(
                'assets/images/479_792.png',
                package: 'parabeac',
                width: 3.186,
                height: 7.640,
                fit: BoxFit.none,
              ),
            ),
            Positioned(
              left: 229.045,
              width: 4.255,
              top: 35.993,
              height: 10.308,
              child: Image.asset(
                'assets/images/479_793.png',
                package: 'parabeac',
                width: 4.255,
                height: 10.308,
                fit: BoxFit.none,
              ),
            ),
            Positioned(
              left: 225.476,
              width: 7.285,
              top: 29.783,
              height: 8.194,
              child: Image.asset(
                'assets/images/479_794.png',
                package: 'parabeac',
                width: 7.285,
                height: 8.194,
                fit: BoxFit.none,
              ),
            ),
            Positioned(
              left: 223.359,
              width: 7.449,
              top: 25.672,
              height: 7.973,
              child: Image.asset(
                'assets/images/479_795.png',
                package: 'parabeac',
                width: 7.449,
                height: 7.973,
                fit: BoxFit.none,
              ),
            ),
            Positioned(
              left: 230.414,
              width: 2.871,
              top: 33.076,
              height: 17.976,
              child: Image.asset(
                'assets/images/479_796.png',
                package: 'parabeac',
                width: 2.871,
                height: 17.976,
                fit: BoxFit.none,
              ),
            ),
            Positioned(
              left: 231.164,
              width: 2.088,
              top: 50.282,
              height: 25.387,
              child: Image.asset(
                'assets/images/479_797.png',
                package: 'parabeac',
                width: 2.088,
                height: 25.387,
                fit: BoxFit.none,
              ),
            ),
            Positioned(
              left: 231.073,
              width: 2.045,
              top: 74.874,
              height: 20.034,
              child: Image.asset(
                'assets/images/479_798.png',
                package: 'parabeac',
                width: 2.045,
                height: 20.034,
                fit: BoxFit.none,
              ),
            ),
            Positioned(
              left: 250.42,
              width: 5.44,
              top: 79.383,
              height: 4.219,
              child: Image.asset(
                'assets/images/479_799.png',
                package: 'parabeac',
                width: 5.440,
                height: 4.219,
                fit: BoxFit.none,
              ),
            ),
            Positioned(
              left: 250.807,
              width: 7.54,
              top: 73.592,
              height: 4.466,
              child: Image.asset(
                'assets/images/479_800.png',
                package: 'parabeac',
                width: 7.540,
                height: 4.466,
                fit: BoxFit.none,
              ),
            ),
            Positioned(
              left: 251.557,
              width: 7.732,
              top: 67.413,
              height: 5.136,
              child: Image.asset(
                'assets/images/479_801.png',
                package: 'parabeac',
                width: 7.732,
                height: 5.136,
                fit: BoxFit.none,
              ),
            ),
            Positioned(
              left: 252.521,
              width: 7.651,
              top: 61.262,
              height: 5.921,
              child: Image.asset(
                'assets/images/479_802.png',
                package: 'parabeac',
                width: 7.651,
                height: 5.921,
                fit: BoxFit.none,
              ),
            ),
            Positioned(
              left: 254.07,
              width: 7.54,
              top: 55.791,
              height: 5.808,
              child: Image.asset(
                'assets/images/479_803.png',
                package: 'parabeac',
                width: 7.540,
                height: 5.808,
                fit: BoxFit.none,
              ),
            ),
            Positioned(
              left: 255.971,
              width: 6.586,
              top: 50.112,
              height: 5.376,
              child: Image.asset(
                'assets/images/479_804.png',
                package: 'parabeac',
                width: 6.586,
                height: 5.376,
                fit: BoxFit.none,
              ),
            ),
            Positioned(
              left: 257.66,
              width: 5.882,
              top: 43.74,
              height: 6.09,
              child: Image.asset(
                'assets/images/479_805.png',
                package: 'parabeac',
                width: 5.882,
                height: 6.090,
                fit: BoxFit.none,
              ),
            ),
            Positioned(
              left: 259.201,
              width: 5.257,
              top: 37.713,
              height: 5.994,
              child: Image.asset(
                'assets/images/479_806.png',
                package: 'parabeac',
                width: 5.257,
                height: 5.994,
                fit: BoxFit.none,
              ),
            ),
            Positioned(
              left: 259.852,
              width: 3.256,
              top: 28.637,
              height: 10.725,
              child: Image.asset(
                'assets/images/479_807.png',
                package: 'parabeac',
                width: 3.256,
                height: 10.725,
                fit: BoxFit.none,
              ),
            ),
            Positioned(
              left: 260.681,
              width: 1.405,
              top: 19.892,
              height: 11.235,
              child: Image.asset(
                'assets/images/479_808.png',
                package: 'parabeac',
                width: 1.405,
                height: 11.235,
                fit: BoxFit.none,
              ),
            ),
            Positioned(
              left: 242.661,
              width: 3.02,
              top: 86.239,
              height: 1.867,
              child: Image.asset(
                'assets/images/479_809.png',
                package: 'parabeac',
                width: 3.020,
                height: 1.867,
                fit: BoxFit.none,
              ),
            ),
            Positioned(
              left: 243.171,
              width: 7.245,
              top: 79.12,
              height: 4.766,
              child: Image.asset(
                'assets/images/479_810.png',
                package: 'parabeac',
                width: 7.245,
                height: 4.766,
                fit: BoxFit.none,
              ),
            ),
            Positioned(
              left: 243.798,
              width: 7.285,
              top: 72.96,
              height: 4.814,
              child: Image.asset(
                'assets/images/479_811.png',
                package: 'parabeac',
                width: 7.285,
                height: 4.814,
                fit: BoxFit.none,
              ),
            ),
            Positioned(
              left: 246.778,
              width: 5.346,
              top: 64.475,
              height: 7.917,
              child: Image.asset(
                'assets/images/479_812.png',
                package: 'parabeac',
                width: 5.346,
                height: 7.917,
                fit: BoxFit.none,
              ),
            ),
            Positioned(
              left: 248.729,
              width: 4.186,
              top: 58.235,
              height: 8.944,
              child: Image.asset(
                'assets/images/479_813.png',
                package: 'parabeac',
                width: 4.186,
                height: 8.944,
                fit: BoxFit.none,
              ),
            ),
            Positioned(
              left: 250.235,
              width: 4.642,
              top: 52.815,
              height: 8.598,
              child: Image.asset(
                'assets/images/479_814.png',
                package: 'parabeac',
                width: 4.642,
                height: 8.598,
                fit: BoxFit.none,
              ),
            ),
            Positioned(
              left: 253.911,
              width: 2.581,
              top: 46.857,
              height: 8.512,
              child: Image.asset(
                'assets/images/479_815.png',
                package: 'parabeac',
                width: 2.581,
                height: 8.512,
                fit: BoxFit.none,
              ),
            ),
            Positioned(
              left: 255.006,
              width: 2.798,
              top: 41.402,
              height: 8.255,
              child: Image.asset(
                'assets/images/479_816.png',
                package: 'parabeac',
                width: 2.798,
                height: 8.255,
                fit: BoxFit.none,
              ),
            ),
            Positioned(
              left: 257.446,
              width: 2.132,
              top: 35.965,
              height: 8.075,
              child: Image.asset(
                'assets/images/479_817.png',
                package: 'parabeac',
                width: 2.132,
                height: 8.075,
                fit: BoxFit.none,
              ),
            ),
            Positioned(
              left: 257.724,
              width: 2.447,
              top: 28.106,
              height: 11.017,
              child: Image.asset(
                'assets/images/479_818.png',
                package: 'parabeac',
                width: 2.447,
                height: 11.017,
                fit: BoxFit.none,
              ),
            ),
            Positioned(
              left: 255.723,
              width: 5.527,
              top: 21.254,
              height: 9.604,
              child: Image.asset(
                'assets/images/479_819.png',
                package: 'parabeac',
                width: 5.527,
                height: 9.604,
                fit: BoxFit.none,
              ),
            ),
            Positioned(
              left: 254.455,
              width: 5.81,
              top: 16.772,
              height: 9.378,
              child: Image.asset(
                'assets/images/479_820.png',
                package: 'parabeac',
                width: 5.810,
                height: 9.378,
                fit: BoxFit.none,
              ),
            ),
            Positioned(
              left: 258.946,
              width: 2.219,
              top: 25.56,
              height: 18.189,
              child: Image.asset(
                'assets/images/479_821.png',
                package: 'parabeac',
                width: 2.219,
                height: 18.189,
                fit: BoxFit.none,
              ),
            ),
            Positioned(
              left: 252.36,
              width: 6.992,
              top: 43.018,
              height: 24.458,
              child: Image.asset(
                'assets/images/479_822.png',
                package: 'parabeac',
                width: 6.992,
                height: 24.458,
                fit: BoxFit.none,
              ),
            ),
            Positioned(
              left: 250.05,
              width: 2.807,
              top: 66.617,
              height: 17.145,
              child: Image.asset(
                'assets/images/479_823.png',
                package: 'parabeac',
                width: 2.807,
                height: 17.145,
                fit: BoxFit.none,
              ),
            ),
          ]),
        ),
      ]),
    );
  }

  @override
  void dispose() {
    super.dispose();
  }
}
