import 'package:flutter/material.dart';
import 'package:auto_size_text/auto_size_text.dart';

class Splashscreenpadi1 extends StatefulWidget {
  const Splashscreenpadi1({Key? key}) : super(key: key);
  @override
  _Splashscreenpadi1 createState() => _Splashscreenpadi1();
}

class _Splashscreenpadi1 extends State<Splashscreenpadi1> {
  _Splashscreenpadi1();

  @override
  Widget build(BuildContext context) {
    return Material(
      color: Colors.white,
      child: Stack(children: [
        Positioned(
          left: MediaQuery.of(context).size.width * 1.094,
          width: MediaQuery.of(context).size.width * 0.106,
          top: MediaQuery.of(context).size.height * 1.142,
          height: MediaQuery.of(context).size.height * 0.031,
          child: Container(
              width: MediaQuery.of(context).size.width * 0.106,
              height: MediaQuery.of(context).size.height * 0.031,
              child: AutoSizeText(
                'Swipe',
                style: TextStyle(
                  fontFamily: 'Poppins',
                  fontSize: 13,
                  fontWeight: FontWeight.w300,
                  fontStyle: FontStyle.italic,
                  letterSpacing: 0,
                  color: Color(0xff3f3d56),
                ),
                textAlign: TextAlign.left,
              )),
        ),
        Positioned(
          left: 0,
          width: 602.074,
          top: 0,
          height: 615.672,
          child: Container(
            width: 602.074,
            height: 615.672,
            decoration: BoxDecoration(
              color: Color(0xff3aa133),
              borderRadius: BorderRadius.all(Radius.circular(25)),
            ),
          ),
        ),
        Positioned(
          left: 331.0,
          width: 111.0,
          top: 218.0,
          height: 14.0,
          child: LayoutBuilder(builder: (context, constraints) {
            return Container(/** This Symbol was not found **/);
          }),
        ),
        Positioned(
          left: MediaQuery.of(context).size.width * 1.222,
          width: MediaQuery.of(context).size.width * 0.028,
          top: MediaQuery.of(context).size.height * 1.148,
          height: MediaQuery.of(context).size.height * 0.024,
          child: Image.asset(
            'assets/images/479_179.png',
            package: 'parabeac',
            width: MediaQuery.of(context).size.width * 0.028,
            height: MediaQuery.of(context).size.height * 0.024,
            fit: BoxFit.fill,
          ),
        ),
        Positioned(
          left: MediaQuery.of(context).size.width * 0.369,
          width: MediaQuery.of(context).size.width * 0.286,
          top: MediaQuery.of(context).size.height * 0.972,
          height: MediaQuery.of(context).size.height * 0.031,
          child: Container(
              width: MediaQuery.of(context).size.width * 0.286,
              height: MediaQuery.of(context).size.height * 0.031,
              child: AutoSizeText(
                'Hello, Welcome!',
                style: TextStyle(
                  fontFamily: 'Poppins',
                  fontSize: 13,
                  fontWeight: FontWeight.w300,
                  fontStyle: FontStyle.italic,
                  letterSpacing: 0,
                  color: Color(0xff1d1d1d),
                ),
                textAlign: TextAlign.left,
              )),
        ),
        Positioned(
          left: MediaQuery.of(context).size.width * 0.364,
          width: MediaQuery.of(context).size.width * 0.731,
          top: MediaQuery.of(context).size.height * 1.05,
          height: MediaQuery.of(context).size.height * 0.031,
          child: Container(
              width: MediaQuery.of(context).size.width * 0.731,
              height: MediaQuery.of(context).size.height * 0.031,
              child: AutoSizeText(
                'Our rides are negotiable and convenient',
                style: TextStyle(
                  fontFamily: 'Poppins',
                  fontSize: 13,
                  fontWeight: FontWeight.w400,
                  fontStyle: FontStyle.normal,
                  letterSpacing: 0,
                  color: Color(0xff1d1d1d),
                ),
                textAlign: TextAlign.left,
              )),
        ),
        Positioned(
          left: MediaQuery.of(context).size.width * 0.367,
          width: MediaQuery.of(context).size.width * 0.622,
          top: MediaQuery.of(context).size.height * 0.998,
          height: MediaQuery.of(context).size.height * 0.052,
          child: Container(
              width: MediaQuery.of(context).size.width * 0.622,
              height: MediaQuery.of(context).size.height * 0.052,
              child: AutoSizeText(
                'Experience Comfort',
                style: TextStyle(
                  fontFamily: 'Poppins',
                  fontSize: 22,
                  fontWeight: FontWeight.w700,
                  fontStyle: FontStyle.normal,
                  letterSpacing: 0,
                  color: Color(0xff1d1d1d),
                ),
                textAlign: TextAlign.right,
              )),
        ),
        Positioned(
          left: 212.0,
          width: 148.0,
          top: 787.0,
          height: 4.0,
          child: Container(
            width: 148.000,
            height: 4.000,
            decoration: BoxDecoration(
              color: Color(0xffc4c4c4),
              borderRadius: BorderRadius.all(Radius.circular(5)),
            ),
          ),
        ),
        Positioned(
          left: 212.0,
          width: 47.0,
          top: 787.0,
          height: 4.0,
          child: Container(
            width: 47.000,
            height: 4.000,
            decoration: BoxDecoration(
              color: Color(0xff3aa133),
              borderRadius: BorderRadius.all(Radius.circular(5)),
            ),
          ),
        ),
        Positioned(
          left: MediaQuery.of(context).size.width * 0.367,
          width: MediaQuery.of(context).size.width * 0.072,
          top: MediaQuery.of(context).size.height * 0.388,
          height: MediaQuery.of(context).size.height * 0.031,
          child: Container(
              width: MediaQuery.of(context).size.width * 0.072,
              height: MediaQuery.of(context).size.height * 0.031,
              child: AutoSizeText(
                'Skip',
                style: TextStyle(
                  fontFamily: 'Poppins',
                  fontSize: 13,
                  fontWeight: FontWeight.w300,
                  fontStyle: FontStyle.italic,
                  letterSpacing: 0,
                  color: Colors.white,
                ),
                textAlign: TextAlign.left,
              )),
        ),
        Positioned(
          left: MediaQuery.of(context).size.width * 0.3,
          width: MediaQuery.of(context).size.width * 1.128,
          top: MediaQuery.of(context).size.height * 0.448,
          height: MediaQuery.of(context).size.height * 0.419,
          child: Image.asset(
            'assets/images/479_181.png',
            package: 'parabeac',
            width: MediaQuery.of(context).size.width * 1.128,
            height: MediaQuery.of(context).size.height * 0.419,
            fit: BoxFit.fill,
          ),
        ),
        Positioned(
          left: MediaQuery.of(context).size.width * 0.361,
          width: 0,
          top: MediaQuery.of(context).size.height * 0.752,
          height: 0,
          child: Image.asset(
            'assets/images/479_182.png',
            package: 'parabeac',
            width: MediaQuery.of(context).size.width * 0.000,
            height: MediaQuery.of(context).size.height * 0.000,
            fit: BoxFit.fill,
          ),
        ),
        Positioned(
          left: MediaQuery.of(context).size.width * 0.538,
          width: MediaQuery.of(context).size.width * 0.01,
          top: MediaQuery.of(context).size.height * 0.788,
          height: MediaQuery.of(context).size.height * 0.002,
          child: Image.asset(
            'assets/images/479_183.png',
            package: 'parabeac',
            width: MediaQuery.of(context).size.width * 0.010,
            height: MediaQuery.of(context).size.height * 0.002,
            fit: BoxFit.fill,
          ),
        ),
        Positioned(
          left: MediaQuery.of(context).size.width * 0.9,
          width: MediaQuery.of(context).size.width * 0.025,
          top: MediaQuery.of(context).size.height * 0.483,
          height: MediaQuery.of(context).size.height * 0.035,
          child: Image.asset(
            'assets/images/479_184.png',
            package: 'parabeac',
            width: MediaQuery.of(context).size.width * 0.025,
            height: MediaQuery.of(context).size.height * 0.035,
            fit: BoxFit.fill,
          ),
        ),
        Positioned(
          left: MediaQuery.of(context).size.width * 0.757,
          width: MediaQuery.of(context).size.width * 0.209,
          top: MediaQuery.of(context).size.height * 0.515,
          height: MediaQuery.of(context).size.height * 0.349,
          child: Image.asset(
            'assets/images/479_185.png',
            package: 'parabeac',
            width: MediaQuery.of(context).size.width * 0.209,
            height: MediaQuery.of(context).size.height * 0.349,
            fit: BoxFit.fill,
          ),
        ),
        Positioned(
          left: MediaQuery.of(context).size.width * 0.967,
          width: MediaQuery.of(context).size.width * 0.084,
          top: MediaQuery.of(context).size.height * 0.515,
          height: MediaQuery.of(context).size.height * 0.352,
          child: Image.asset(
            'assets/images/479_186.png',
            package: 'parabeac',
            width: MediaQuery.of(context).size.width * 0.084,
            height: MediaQuery.of(context).size.height * 0.352,
            fit: BoxFit.fill,
          ),
        ),
        Positioned(
          left: MediaQuery.of(context).size.width * 0.795,
          width: MediaQuery.of(context).size.width * 0.032,
          top: MediaQuery.of(context).size.height * 0.55,
          height: MediaQuery.of(context).size.height * 0.018,
          child: Image.asset(
            'assets/images/479_187.png',
            package: 'parabeac',
            width: MediaQuery.of(context).size.width * 0.032,
            height: MediaQuery.of(context).size.height * 0.018,
            fit: BoxFit.fill,
          ),
        ),
        Positioned(
          left: MediaQuery.of(context).size.width * 0.846,
          width: MediaQuery.of(context).size.width * 0.032,
          top: MediaQuery.of(context).size.height * 0.55,
          height: MediaQuery.of(context).size.height * 0.018,
          child: Image.asset(
            'assets/images/479_188.png',
            package: 'parabeac',
            width: MediaQuery.of(context).size.width * 0.032,
            height: MediaQuery.of(context).size.height * 0.018,
            fit: BoxFit.fill,
          ),
        ),
        Positioned(
          left: MediaQuery.of(context).size.width * 0.897,
          width: MediaQuery.of(context).size.width * 0.032,
          top: MediaQuery.of(context).size.height * 0.55,
          height: MediaQuery.of(context).size.height * 0.018,
          child: Image.asset(
            'assets/images/479_189.png',
            package: 'parabeac',
            width: MediaQuery.of(context).size.width * 0.032,
            height: MediaQuery.of(context).size.height * 0.018,
            fit: BoxFit.fill,
          ),
        ),
        Positioned(
          left: MediaQuery.of(context).size.width * 0.796,
          width: MediaQuery.of(context).size.width * 0.032,
          top: MediaQuery.of(context).size.height * 0.59,
          height: MediaQuery.of(context).size.height * 0.018,
          child: Image.asset(
            'assets/images/479_190.png',
            package: 'parabeac',
            width: MediaQuery.of(context).size.width * 0.032,
            height: MediaQuery.of(context).size.height * 0.018,
            fit: BoxFit.fill,
          ),
        ),
        Positioned(
          left: MediaQuery.of(context).size.width * 0.847,
          width: MediaQuery.of(context).size.width * 0.032,
          top: MediaQuery.of(context).size.height * 0.59,
          height: MediaQuery.of(context).size.height * 0.018,
          child: Image.asset(
            'assets/images/479_191.png',
            package: 'parabeac',
            width: MediaQuery.of(context).size.width * 0.032,
            height: MediaQuery.of(context).size.height * 0.018,
            fit: BoxFit.fill,
          ),
        ),
        Positioned(
          left: MediaQuery.of(context).size.width * 0.898,
          width: MediaQuery.of(context).size.width * 0.032,
          top: MediaQuery.of(context).size.height * 0.59,
          height: MediaQuery.of(context).size.height * 0.018,
          child: Image.asset(
            'assets/images/479_192.png',
            package: 'parabeac',
            width: MediaQuery.of(context).size.width * 0.032,
            height: MediaQuery.of(context).size.height * 0.018,
            fit: BoxFit.fill,
          ),
        ),
        Positioned(
          left: MediaQuery.of(context).size.width * 0.797,
          width: MediaQuery.of(context).size.width * 0.032,
          top: MediaQuery.of(context).size.height * 0.631,
          height: MediaQuery.of(context).size.height * 0.018,
          child: Image.asset(
            'assets/images/479_193.png',
            package: 'parabeac',
            width: MediaQuery.of(context).size.width * 0.032,
            height: MediaQuery.of(context).size.height * 0.018,
            fit: BoxFit.fill,
          ),
        ),
        Positioned(
          left: MediaQuery.of(context).size.width * 0.848,
          width: MediaQuery.of(context).size.width * 0.032,
          top: MediaQuery.of(context).size.height * 0.631,
          height: MediaQuery.of(context).size.height * 0.018,
          child: Image.asset(
            'assets/images/479_194.png',
            package: 'parabeac',
            width: MediaQuery.of(context).size.width * 0.032,
            height: MediaQuery.of(context).size.height * 0.018,
            fit: BoxFit.fill,
          ),
        ),
        Positioned(
          left: MediaQuery.of(context).size.width * 0.899,
          width: MediaQuery.of(context).size.width * 0.032,
          top: MediaQuery.of(context).size.height * 0.631,
          height: MediaQuery.of(context).size.height * 0.018,
          child: Image.asset(
            'assets/images/479_195.png',
            package: 'parabeac',
            width: MediaQuery.of(context).size.width * 0.032,
            height: MediaQuery.of(context).size.height * 0.018,
            fit: BoxFit.fill,
          ),
        ),
        Positioned(
          left: MediaQuery.of(context).size.width * 0.798,
          width: MediaQuery.of(context).size.width * 0.032,
          top: MediaQuery.of(context).size.height * 0.672,
          height: MediaQuery.of(context).size.height * 0.018,
          child: Image.asset(
            'assets/images/479_196.png',
            package: 'parabeac',
            width: MediaQuery.of(context).size.width * 0.032,
            height: MediaQuery.of(context).size.height * 0.018,
            fit: BoxFit.fill,
          ),
        ),
        Positioned(
          left: MediaQuery.of(context).size.width * 0.849,
          width: MediaQuery.of(context).size.width * 0.032,
          top: MediaQuery.of(context).size.height * 0.672,
          height: MediaQuery.of(context).size.height * 0.018,
          child: Image.asset(
            'assets/images/479_197.png',
            package: 'parabeac',
            width: MediaQuery.of(context).size.width * 0.032,
            height: MediaQuery.of(context).size.height * 0.018,
            fit: BoxFit.fill,
          ),
        ),
        Positioned(
          left: MediaQuery.of(context).size.width * 0.9,
          width: MediaQuery.of(context).size.width * 0.032,
          top: MediaQuery.of(context).size.height * 0.672,
          height: MediaQuery.of(context).size.height * 0.018,
          child: Image.asset(
            'assets/images/479_198.png',
            package: 'parabeac',
            width: MediaQuery.of(context).size.width * 0.032,
            height: MediaQuery.of(context).size.height * 0.018,
            fit: BoxFit.fill,
          ),
        ),
        Positioned(
          left: MediaQuery.of(context).size.width * 0.799,
          width: MediaQuery.of(context).size.width * 0.032,
          top: MediaQuery.of(context).size.height * 0.712,
          height: MediaQuery.of(context).size.height * 0.018,
          child: Image.asset(
            'assets/images/479_199.png',
            package: 'parabeac',
            width: MediaQuery.of(context).size.width * 0.032,
            height: MediaQuery.of(context).size.height * 0.018,
            fit: BoxFit.fill,
          ),
        ),
        Positioned(
          left: MediaQuery.of(context).size.width * 0.85,
          width: MediaQuery.of(context).size.width * 0.032,
          top: MediaQuery.of(context).size.height * 0.712,
          height: MediaQuery.of(context).size.height * 0.018,
          child: Image.asset(
            'assets/images/479_200.png',
            package: 'parabeac',
            width: MediaQuery.of(context).size.width * 0.032,
            height: MediaQuery.of(context).size.height * 0.018,
            fit: BoxFit.fill,
          ),
        ),
        Positioned(
          left: MediaQuery.of(context).size.width * 0.901,
          width: MediaQuery.of(context).size.width * 0.032,
          top: MediaQuery.of(context).size.height * 0.712,
          height: MediaQuery.of(context).size.height * 0.018,
          child: Image.asset(
            'assets/images/479_201.png',
            package: 'parabeac',
            width: MediaQuery.of(context).size.width * 0.032,
            height: MediaQuery.of(context).size.height * 0.018,
            fit: BoxFit.fill,
          ),
        ),
        Positioned(
          left: MediaQuery.of(context).size.width * 0.8,
          width: MediaQuery.of(context).size.width * 0.032,
          top: MediaQuery.of(context).size.height * 0.753,
          height: MediaQuery.of(context).size.height * 0.018,
          child: Image.asset(
            'assets/images/479_202.png',
            package: 'parabeac',
            width: MediaQuery.of(context).size.width * 0.032,
            height: MediaQuery.of(context).size.height * 0.018,
            fit: BoxFit.fill,
          ),
        ),
        Positioned(
          left: MediaQuery.of(context).size.width * 0.851,
          width: MediaQuery.of(context).size.width * 0.032,
          top: MediaQuery.of(context).size.height * 0.753,
          height: MediaQuery.of(context).size.height * 0.018,
          child: Image.asset(
            'assets/images/479_203.png',
            package: 'parabeac',
            width: MediaQuery.of(context).size.width * 0.032,
            height: MediaQuery.of(context).size.height * 0.018,
            fit: BoxFit.fill,
          ),
        ),
        Positioned(
          left: MediaQuery.of(context).size.width * 0.902,
          width: MediaQuery.of(context).size.width * 0.032,
          top: MediaQuery.of(context).size.height * 0.753,
          height: MediaQuery.of(context).size.height * 0.018,
          child: Image.asset(
            'assets/images/479_204.png',
            package: 'parabeac',
            width: MediaQuery.of(context).size.width * 0.032,
            height: MediaQuery.of(context).size.height * 0.018,
            fit: BoxFit.fill,
          ),
        ),
        Positioned(
          left: MediaQuery.of(context).size.width * 0.801,
          width: MediaQuery.of(context).size.width * 0.032,
          top: MediaQuery.of(context).size.height * 0.793,
          height: MediaQuery.of(context).size.height * 0.018,
          child: Image.asset(
            'assets/images/479_205.png',
            package: 'parabeac',
            width: MediaQuery.of(context).size.width * 0.032,
            height: MediaQuery.of(context).size.height * 0.018,
            fit: BoxFit.fill,
          ),
        ),
        Positioned(
          left: MediaQuery.of(context).size.width * 0.852,
          width: MediaQuery.of(context).size.width * 0.032,
          top: MediaQuery.of(context).size.height * 0.793,
          height: MediaQuery.of(context).size.height * 0.018,
          child: Image.asset(
            'assets/images/479_206.png',
            package: 'parabeac',
            width: MediaQuery.of(context).size.width * 0.032,
            height: MediaQuery.of(context).size.height * 0.018,
            fit: BoxFit.fill,
          ),
        ),
        Positioned(
          left: MediaQuery.of(context).size.width * 0.903,
          width: MediaQuery.of(context).size.width * 0.032,
          top: MediaQuery.of(context).size.height * 0.793,
          height: MediaQuery.of(context).size.height * 0.018,
          child: Image.asset(
            'assets/images/479_207.png',
            package: 'parabeac',
            width: MediaQuery.of(context).size.width * 0.032,
            height: MediaQuery.of(context).size.height * 0.018,
            fit: BoxFit.fill,
          ),
        ),
        Positioned(
          left: MediaQuery.of(context).size.width * 0.801,
          width: MediaQuery.of(context).size.width * 0.032,
          top: MediaQuery.of(context).size.height * 0.834,
          height: MediaQuery.of(context).size.height * 0.009,
          child: Image.asset(
            'assets/images/479_208.png',
            package: 'parabeac',
            width: MediaQuery.of(context).size.width * 0.032,
            height: MediaQuery.of(context).size.height * 0.009,
            fit: BoxFit.fill,
          ),
        ),
        Positioned(
          left: MediaQuery.of(context).size.width * 0.852,
          width: MediaQuery.of(context).size.width * 0.032,
          top: MediaQuery.of(context).size.height * 0.834,
          height: MediaQuery.of(context).size.height * 0.018,
          child: Image.asset(
            'assets/images/479_209.png',
            package: 'parabeac',
            width: MediaQuery.of(context).size.width * 0.032,
            height: MediaQuery.of(context).size.height * 0.018,
            fit: BoxFit.fill,
          ),
        ),
        Positioned(
          left: MediaQuery.of(context).size.width * 0.903,
          width: MediaQuery.of(context).size.width * 0.032,
          top: MediaQuery.of(context).size.height * 0.834,
          height: MediaQuery.of(context).size.height * 0.018,
          child: Image.asset(
            'assets/images/479_210.png',
            package: 'parabeac',
            width: MediaQuery.of(context).size.width * 0.032,
            height: MediaQuery.of(context).size.height * 0.018,
            fit: BoxFit.fill,
          ),
        ),
        Positioned(
          left: MediaQuery.of(context).size.width * 1.187,
          width: MediaQuery.of(context).size.width * 0.025,
          top: MediaQuery.of(context).size.height * 0.66,
          height: MediaQuery.of(context).size.height * 0.021,
          child: Image.asset(
            'assets/images/479_211.png',
            package: 'parabeac',
            width: MediaQuery.of(context).size.width * 0.025,
            height: MediaQuery.of(context).size.height * 0.021,
            fit: BoxFit.fill,
          ),
        ),
        Positioned(
          left: MediaQuery.of(context).size.width * 1.021,
          width: MediaQuery.of(context).size.width * 0.209,
          top: MediaQuery.of(context).size.height * 0.678,
          height: MediaQuery.of(context).size.height * 0.189,
          child: Image.asset(
            'assets/images/479_212.png',
            package: 'parabeac',
            width: MediaQuery.of(context).size.width * 0.209,
            height: MediaQuery.of(context).size.height * 0.189,
            fit: BoxFit.fill,
          ),
        ),
        Positioned(
          left: MediaQuery.of(context).size.width * 1.231,
          width: MediaQuery.of(context).size.width * 0.084,
          top: MediaQuery.of(context).size.height * 0.678,
          height: MediaQuery.of(context).size.height * 0.172,
          child: Image.asset(
            'assets/images/479_213.png',
            package: 'parabeac',
            width: MediaQuery.of(context).size.width * 0.084,
            height: MediaQuery.of(context).size.height * 0.172,
            fit: BoxFit.fill,
          ),
        ),
        Positioned(
          left: MediaQuery.of(context).size.width * 1.063,
          width: MediaQuery.of(context).size.width * 0.032,
          top: MediaQuery.of(context).size.height * 0.712,
          height: MediaQuery.of(context).size.height * 0.018,
          child: Image.asset(
            'assets/images/479_214.png',
            package: 'parabeac',
            width: MediaQuery.of(context).size.width * 0.032,
            height: MediaQuery.of(context).size.height * 0.018,
            fit: BoxFit.fill,
          ),
        ),
        Positioned(
          left: MediaQuery.of(context).size.width * 1.114,
          width: MediaQuery.of(context).size.width * 0.032,
          top: MediaQuery.of(context).size.height * 0.712,
          height: MediaQuery.of(context).size.height * 0.018,
          child: Image.asset(
            'assets/images/479_215.png',
            package: 'parabeac',
            width: MediaQuery.of(context).size.width * 0.032,
            height: MediaQuery.of(context).size.height * 0.018,
            fit: BoxFit.fill,
          ),
        ),
        Positioned(
          left: MediaQuery.of(context).size.width * 1.165,
          width: MediaQuery.of(context).size.width * 0.032,
          top: MediaQuery.of(context).size.height * 0.712,
          height: MediaQuery.of(context).size.height * 0.018,
          child: Image.asset(
            'assets/images/479_216.png',
            package: 'parabeac',
            width: MediaQuery.of(context).size.width * 0.032,
            height: MediaQuery.of(context).size.height * 0.018,
            fit: BoxFit.fill,
          ),
        ),
        Positioned(
          left: MediaQuery.of(context).size.width * 1.064,
          width: MediaQuery.of(context).size.width * 0.032,
          top: MediaQuery.of(context).size.height * 0.753,
          height: MediaQuery.of(context).size.height * 0.018,
          child: Image.asset(
            'assets/images/479_217.png',
            package: 'parabeac',
            width: MediaQuery.of(context).size.width * 0.032,
            height: MediaQuery.of(context).size.height * 0.018,
            fit: BoxFit.fill,
          ),
        ),
        Positioned(
          left: MediaQuery.of(context).size.width * 1.115,
          width: MediaQuery.of(context).size.width * 0.032,
          top: MediaQuery.of(context).size.height * 0.753,
          height: MediaQuery.of(context).size.height * 0.018,
          child: Image.asset(
            'assets/images/479_218.png',
            package: 'parabeac',
            width: MediaQuery.of(context).size.width * 0.032,
            height: MediaQuery.of(context).size.height * 0.018,
            fit: BoxFit.fill,
          ),
        ),
        Positioned(
          left: MediaQuery.of(context).size.width * 1.166,
          width: MediaQuery.of(context).size.width * 0.032,
          top: MediaQuery.of(context).size.height * 0.753,
          height: MediaQuery.of(context).size.height * 0.018,
          child: Image.asset(
            'assets/images/479_219.png',
            package: 'parabeac',
            width: MediaQuery.of(context).size.width * 0.032,
            height: MediaQuery.of(context).size.height * 0.018,
            fit: BoxFit.fill,
          ),
        ),
        Positioned(
          left: MediaQuery.of(context).size.width * 1.064,
          width: MediaQuery.of(context).size.width * 0.032,
          top: MediaQuery.of(context).size.height * 0.793,
          height: MediaQuery.of(context).size.height * 0.018,
          child: Image.asset(
            'assets/images/479_220.png',
            package: 'parabeac',
            width: MediaQuery.of(context).size.width * 0.032,
            height: MediaQuery.of(context).size.height * 0.018,
            fit: BoxFit.fill,
          ),
        ),
        Positioned(
          left: MediaQuery.of(context).size.width * 1.116,
          width: MediaQuery.of(context).size.width * 0.032,
          top: MediaQuery.of(context).size.height * 0.793,
          height: MediaQuery.of(context).size.height * 0.018,
          child: Image.asset(
            'assets/images/479_221.png',
            package: 'parabeac',
            width: MediaQuery.of(context).size.width * 0.032,
            height: MediaQuery.of(context).size.height * 0.018,
            fit: BoxFit.fill,
          ),
        ),
        Positioned(
          left: MediaQuery.of(context).size.width * 1.167,
          width: MediaQuery.of(context).size.width * 0.032,
          top: MediaQuery.of(context).size.height * 0.793,
          height: MediaQuery.of(context).size.height * 0.018,
          child: Image.asset(
            'assets/images/479_222.png',
            package: 'parabeac',
            width: MediaQuery.of(context).size.width * 0.032,
            height: MediaQuery.of(context).size.height * 0.018,
            fit: BoxFit.fill,
          ),
        ),
        Positioned(
          left: MediaQuery.of(context).size.width * 1.065,
          width: MediaQuery.of(context).size.width * 0.032,
          top: MediaQuery.of(context).size.height * 0.834,
          height: MediaQuery.of(context).size.height * 0.018,
          child: Image.asset(
            'assets/images/479_223.png',
            package: 'parabeac',
            width: MediaQuery.of(context).size.width * 0.032,
            height: MediaQuery.of(context).size.height * 0.018,
            fit: BoxFit.fill,
          ),
        ),
        Positioned(
          left: MediaQuery.of(context).size.width * 1.116,
          width: MediaQuery.of(context).size.width * 0.032,
          top: MediaQuery.of(context).size.height * 0.834,
          height: MediaQuery.of(context).size.height * 0.018,
          child: Image.asset(
            'assets/images/479_224.png',
            package: 'parabeac',
            width: MediaQuery.of(context).size.width * 0.032,
            height: MediaQuery.of(context).size.height * 0.018,
            fit: BoxFit.fill,
          ),
        ),
        Positioned(
          left: MediaQuery.of(context).size.width * 1.167,
          width: MediaQuery.of(context).size.width * 0.032,
          top: MediaQuery.of(context).size.height * 0.834,
          height: MediaQuery.of(context).size.height * 0.018,
          child: Image.asset(
            'assets/images/479_225.png',
            package: 'parabeac',
            width: MediaQuery.of(context).size.width * 0.032,
            height: MediaQuery.of(context).size.height * 0.018,
            fit: BoxFit.fill,
          ),
        ),
        Positioned(
          left: MediaQuery.of(context).size.width * 1.046,
          width: MediaQuery.of(context).size.width * 0.126,
          top: MediaQuery.of(context).size.height * 0.873,
          height: MediaQuery.of(context).size.height * 0.022,
          child: Image.asset(
            'assets/images/479_226.png',
            package: 'parabeac',
            width: MediaQuery.of(context).size.width * 0.126,
            height: MediaQuery.of(context).size.height * 0.022,
            fit: BoxFit.fill,
          ),
        ),
        Positioned(
          left: MediaQuery.of(context).size.width * 0.382,
          width: MediaQuery.of(context).size.width * 0.466,
          top: MediaQuery.of(context).size.height * 0.774,
          height: MediaQuery.of(context).size.height * 0.114,
          child: Image.asset(
            'assets/images/479_227.png',
            package: 'parabeac',
            width: MediaQuery.of(context).size.width * 0.466,
            height: MediaQuery.of(context).size.height * 0.114,
            fit: BoxFit.fill,
          ),
        ),
        Positioned(
          left: MediaQuery.of(context).size.width * 0.384,
          width: MediaQuery.of(context).size.width * 0.098,
          top: MediaQuery.of(context).size.height * 0.794,
          height: MediaQuery.of(context).size.height * 0.082,
          child: Image.asset(
            'assets/images/479_228.png',
            package: 'parabeac',
            width: MediaQuery.of(context).size.width * 0.098,
            height: MediaQuery.of(context).size.height * 0.082,
            fit: BoxFit.fill,
          ),
        ),
        Positioned(
          left: MediaQuery.of(context).size.width * 0.712,
          width: MediaQuery.of(context).size.width * 0.141,
          top: MediaQuery.of(context).size.height * 0.81,
          height: MediaQuery.of(context).size.height * 0.102,
          child: Image.asset(
            'assets/images/479_229.png',
            package: 'parabeac',
            width: MediaQuery.of(context).size.width * 0.141,
            height: MediaQuery.of(context).size.height * 0.102,
            fit: BoxFit.fill,
          ),
        ),
        Positioned(
          left: MediaQuery.of(context).size.width * 0.381,
          width: MediaQuery.of(context).size.width * 0.82,
          top: MediaQuery.of(context).size.height * 0.766,
          height: MediaQuery.of(context).size.height * 0.124,
          child: Image.asset(
            'assets/images/479_230.png',
            package: 'parabeac',
            width: MediaQuery.of(context).size.width * 0.820,
            height: MediaQuery.of(context).size.height * 0.124,
            fit: BoxFit.fill,
          ),
        ),
        Positioned(
          left: MediaQuery.of(context).size.width * 0.429,
          width: MediaQuery.of(context).size.width * 0.574,
          top: MediaQuery.of(context).size.height * 0.695,
          height: MediaQuery.of(context).size.height * 0.066,
          child: Image.asset(
            'assets/images/479_231.png',
            package: 'parabeac',
            width: MediaQuery.of(context).size.width * 0.574,
            height: MediaQuery.of(context).size.height * 0.066,
            fit: BoxFit.fill,
          ),
        ),
        Positioned(
          left: MediaQuery.of(context).size.width * 0.389,
          width: MediaQuery.of(context).size.width * 0.816,
          top: MediaQuery.of(context).size.height * 0.742,
          height: MediaQuery.of(context).size.height * 0.137,
          child: Image.asset(
            'assets/images/479_232.png',
            package: 'parabeac',
            width: MediaQuery.of(context).size.width * 0.816,
            height: MediaQuery.of(context).size.height * 0.137,
            fit: BoxFit.fill,
          ),
        ),
        Positioned(
          left: MediaQuery.of(context).size.width * 0.503,
          width: MediaQuery.of(context).size.width * 0.035,
          top: MediaQuery.of(context).size.height * 0.765,
          height: MediaQuery.of(context).size.height * 0.006,
          child: Image.asset(
            'assets/images/479_233.png',
            package: 'parabeac',
            width: MediaQuery.of(context).size.width * 0.035,
            height: MediaQuery.of(context).size.height * 0.006,
            fit: BoxFit.fill,
          ),
        ),
        Positioned(
          left: MediaQuery.of(context).size.width * 0.894,
          width: MediaQuery.of(context).size.width * 0.032,
          top: MediaQuery.of(context).size.height * 0.842,
          height: MediaQuery.of(context).size.height * 0.018,
          child: Image.asset(
            'assets/images/479_234.png',
            package: 'parabeac',
            width: MediaQuery.of(context).size.width * 0.032,
            height: MediaQuery.of(context).size.height * 0.018,
            fit: BoxFit.fill,
          ),
        ),
        Positioned(
          left: MediaQuery.of(context).size.width * 0.843,
          width: MediaQuery.of(context).size.width * 0.083,
          top: MediaQuery.of(context).size.height * 0.765,
          height: MediaQuery.of(context).size.height * 0.042,
          child: Image.asset(
            'assets/images/479_235.png',
            package: 'parabeac',
            width: MediaQuery.of(context).size.width * 0.083,
            height: MediaQuery.of(context).size.height * 0.042,
            fit: BoxFit.fill,
          ),
        ),
        Positioned(
          left: MediaQuery.of(context).size.width * 1.126,
          width: MediaQuery.of(context).size.width * 0.068,
          top: MediaQuery.of(context).size.height * 0.76,
          height: MediaQuery.of(context).size.height * 0.036,
          child: Image.asset(
            'assets/images/479_236.png',
            package: 'parabeac',
            width: MediaQuery.of(context).size.width * 0.068,
            height: MediaQuery.of(context).size.height * 0.036,
            fit: BoxFit.fill,
          ),
        ),
        Positioned(
          left: MediaQuery.of(context).size.width * 0.451,
          width: MediaQuery.of(context).size.width * 0.08,
          top: MediaQuery.of(context).size.height * 0.705,
          height: MediaQuery.of(context).size.height * 0.037,
          child: Image.asset(
            'assets/images/479_237.png',
            package: 'parabeac',
            width: MediaQuery.of(context).size.width * 0.080,
            height: MediaQuery.of(context).size.height * 0.037,
            fit: BoxFit.fill,
          ),
        ),
        Positioned(
          left: MediaQuery.of(context).size.width * 0.541,
          width: MediaQuery.of(context).size.width * 0.124,
          top: MediaQuery.of(context).size.height * 0.697,
          height: MediaQuery.of(context).size.height * 0.051,
          child: Image.asset(
            'assets/images/479_238.png',
            package: 'parabeac',
            width: MediaQuery.of(context).size.width * 0.124,
            height: MediaQuery.of(context).size.height * 0.051,
            fit: BoxFit.fill,
          ),
        ),
        Positioned(
          left: MediaQuery.of(context).size.width * 0.692,
          width: MediaQuery.of(context).size.width * 0.276,
          top: MediaQuery.of(context).size.height * 0.698,
          height: MediaQuery.of(context).size.height * 0.052,
          child: Image.asset(
            'assets/images/479_239.png',
            package: 'parabeac',
            width: MediaQuery.of(context).size.width * 0.276,
            height: MediaQuery.of(context).size.height * 0.052,
            fit: BoxFit.fill,
          ),
        ),
        Positioned(
          left: MediaQuery.of(context).size.width * 0.478,
          width: MediaQuery.of(context).size.width * 0.421,
          top: MediaQuery.of(context).size.height * 0.683,
          height: MediaQuery.of(context).size.height * 0.02,
          child: Image.asset(
            'assets/images/479_240.png',
            package: 'parabeac',
            width: MediaQuery.of(context).size.width * 0.421,
            height: MediaQuery.of(context).size.height * 0.020,
            fit: BoxFit.fill,
          ),
        ),
        Positioned(
          left: MediaQuery.of(context).size.width * 0.392,
          width: MediaQuery.of(context).size.width * 0.05,
          top: MediaQuery.of(context).size.height * 0.808,
          height: MediaQuery.of(context).size.height * 0.057,
          child: Image.asset(
            'assets/images/479_241.png',
            package: 'parabeac',
            width: MediaQuery.of(context).size.width * 0.050,
            height: MediaQuery.of(context).size.height * 0.057,
            fit: BoxFit.fill,
          ),
        ),
        Positioned(
          left: MediaQuery.of(context).size.width * 0.723,
          width: MediaQuery.of(context).size.width * 0.079,
          top: MediaQuery.of(context).size.height * 0.827,
          height: MediaQuery.of(context).size.height * 0.073,
          child: Image.asset(
            'assets/images/479_242.png',
            package: 'parabeac',
            width: MediaQuery.of(context).size.width * 0.079,
            height: MediaQuery.of(context).size.height * 0.073,
            fit: BoxFit.fill,
          ),
        ),
        Positioned(
          left: MediaQuery.of(context).size.width * 0.625,
          width: MediaQuery.of(context).size.width * 0.033,
          top: MediaQuery.of(context).size.height * 0.747,
          height: MediaQuery.of(context).size.height * 0.019,
          child: Image.asset(
            'assets/images/479_243.png',
            package: 'parabeac',
            width: MediaQuery.of(context).size.width * 0.033,
            height: MediaQuery.of(context).size.height * 0.019,
            fit: BoxFit.fill,
          ),
        ),
        Positioned(
          left: MediaQuery.of(context).size.width * 0.585,
          width: MediaQuery.of(context).size.width * 0.057,
          top: MediaQuery.of(context).size.height * 0.735,
          height: MediaQuery.of(context).size.height * 0.021,
          child: Image.asset(
            'assets/images/479_244.png',
            package: 'parabeac',
            width: MediaQuery.of(context).size.width * 0.057,
            height: MediaQuery.of(context).size.height * 0.021,
            fit: BoxFit.fill,
          ),
        ),
        Positioned(
          left: MediaQuery.of(context).size.width * 0.959,
          width: MediaQuery.of(context).size.width * 0.239,
          top: MediaQuery.of(context).size.height * 0.794,
          height: MediaQuery.of(context).size.height * 0.038,
          child: Image.asset(
            'assets/images/479_245.png',
            package: 'parabeac',
            width: MediaQuery.of(context).size.width * 0.239,
            height: MediaQuery.of(context).size.height * 0.038,
            fit: BoxFit.fill,
          ),
        ),
        Positioned(
          left: MediaQuery.of(context).size.width * 0.984,
          width: MediaQuery.of(context).size.width * 0.191,
          top: MediaQuery.of(context).size.height * 0.799,
          height: MediaQuery.of(context).size.height * 0.005,
          child: Image.asset(
            'assets/images/479_246.png',
            package: 'parabeac',
            width: MediaQuery.of(context).size.width * 0.191,
            height: MediaQuery.of(context).size.height * 0.005,
            fit: BoxFit.fill,
          ),
        ),
        Positioned(
          left: MediaQuery.of(context).size.width * 0.974,
          width: MediaQuery.of(context).size.width * 0.208,
          top: MediaQuery.of(context).size.height * 0.803,
          height: MediaQuery.of(context).size.height * 0.007,
          child: Image.asset(
            'assets/images/479_247.png',
            package: 'parabeac',
            width: MediaQuery.of(context).size.width * 0.208,
            height: MediaQuery.of(context).size.height * 0.007,
            fit: BoxFit.fill,
          ),
        ),
        Positioned(
          left: MediaQuery.of(context).size.width * 0.966,
          width: MediaQuery.of(context).size.width * 0.223,
          top: MediaQuery.of(context).size.height * 0.808,
          height: MediaQuery.of(context).size.height * 0.008,
          child: Image.asset(
            'assets/images/479_248.png',
            package: 'parabeac',
            width: MediaQuery.of(context).size.width * 0.223,
            height: MediaQuery.of(context).size.height * 0.008,
            fit: BoxFit.fill,
          ),
        ),
        Positioned(
          left: MediaQuery.of(context).size.width * 0.294,
          width: MediaQuery.of(context).size.width * 0.259,
          top: MediaQuery.of(context).size.height * 0.654,
          height: MediaQuery.of(context).size.height * 0.237,
          child: Image.asset(
            'assets/images/479_249.png',
            package: 'parabeac',
            width: MediaQuery.of(context).size.width * 0.259,
            height: MediaQuery.of(context).size.height * 0.237,
            fit: BoxFit.fill,
          ),
        ),
      ]),
    );
  }

  @override
  void dispose() {
    super.dispose();
  }
}
