import 'package:flutter/material.dart';
import 'package:auto_size_text/auto_size_text.dart';

class Splashscreen11 extends StatefulWidget {
  const Splashscreen11({Key? key}) : super(key: key);
  @override
  _Splashscreen11 createState() => _Splashscreen11();
}

class _Splashscreen11 extends State<Splashscreen11> {
  _Splashscreen11();

  @override
  Widget build(BuildContext context) {
    return Material(
      color: Colors.white,
      child: Stack(children: [
        Positioned(
          left: MediaQuery.of(context).size.width * 1.531,
          width: MediaQuery.of(context).size.width * 0.106,
          top: MediaQuery.of(context).size.height * 1.142,
          height: MediaQuery.of(context).size.height * 0.031,
          child: Container(
              width: MediaQuery.of(context).size.width * 0.106,
              height: MediaQuery.of(context).size.height * 0.031,
              child: AutoSizeText(
                'Swipe',
                style: TextStyle(
                  fontFamily: 'Poppins',
                  fontSize: 13,
                  fontWeight: FontWeight.w300,
                  fontStyle: FontStyle.italic,
                  letterSpacing: 0,
                  color: Color(0xff3f3d56),
                ),
                textAlign: TextAlign.left,
              )),
        ),
        Positioned(
          left: 157.0,
          width: 602.074,
          top: 0,
          height: 615.672,
          child: Container(
            width: 602.074,
            height: 615.672,
            decoration: BoxDecoration(
              color: Color(0xff3aa133),
              borderRadius: BorderRadius.all(Radius.circular(25)),
            ),
          ),
        ),
        Positioned(
          left: 488.0,
          width: 111.0,
          top: 218.0,
          height: 14.0,
          child: LayoutBuilder(builder: (context, constraints) {
            return Container(/** This Symbol was not found **/);
          }),
        ),
        Positioned(
          left: MediaQuery.of(context).size.width * 1.658,
          width: MediaQuery.of(context).size.width * 0.028,
          top: MediaQuery.of(context).size.height * 1.148,
          height: MediaQuery.of(context).size.height * 0.024,
          child: Image.asset(
            'assets/images/481_1269.png',
            package: 'parabeac',
            width: MediaQuery.of(context).size.width * 0.028,
            height: MediaQuery.of(context).size.height * 0.024,
            fit: BoxFit.fill,
          ),
        ),
        Positioned(
          left: MediaQuery.of(context).size.width * 0.806,
          width: MediaQuery.of(context).size.width * 0.286,
          top: MediaQuery.of(context).size.height * 0.972,
          height: MediaQuery.of(context).size.height * 0.031,
          child: Container(
              width: MediaQuery.of(context).size.width * 0.286,
              height: MediaQuery.of(context).size.height * 0.031,
              child: AutoSizeText(
                'Hello, Welcome!',
                style: TextStyle(
                  fontFamily: 'Poppins',
                  fontSize: 13,
                  fontWeight: FontWeight.w300,
                  fontStyle: FontStyle.italic,
                  letterSpacing: 0,
                  color: Color(0xff1d1d1d),
                ),
                textAlign: TextAlign.left,
              )),
        ),
        Positioned(
          left: 0,
          width: MediaQuery.of(context).size.width * 0.731,
          top: MediaQuery.of(context).size.height * 1.05,
          height: MediaQuery.of(context).size.height * 0.031,
          child: Container(
              width: MediaQuery.of(context).size.width * 0.731,
              height: MediaQuery.of(context).size.height * 0.031,
              child: AutoSizeText(
                'Our rides are negotiable and convenient',
                style: TextStyle(
                  fontFamily: 'Poppins',
                  fontSize: 13,
                  fontWeight: FontWeight.w400,
                  fontStyle: FontStyle.normal,
                  letterSpacing: 0,
                  color: Color(0xff1d1d1d),
                ),
                textAlign: TextAlign.left,
              )),
        ),
        Positioned(
          left: MediaQuery.of(context).size.width * 0.003,
          width: MediaQuery.of(context).size.width * 0.622,
          top: MediaQuery.of(context).size.height * 0.998,
          height: MediaQuery.of(context).size.height * 0.052,
          child: Container(
              width: MediaQuery.of(context).size.width * 0.622,
              height: MediaQuery.of(context).size.height * 0.052,
              child: AutoSizeText(
                'Experience Comfort',
                style: TextStyle(
                  fontFamily: 'Poppins',
                  fontSize: 22,
                  fontWeight: FontWeight.w700,
                  fontStyle: FontStyle.normal,
                  letterSpacing: 0,
                  color: Color(0xff1d1d1d),
                ),
                textAlign: TextAlign.right,
              )),
        ),
        Positioned(
          left: 369.0,
          width: 148.0,
          top: 787.0,
          height: 4.0,
          child: Container(
            width: 148.000,
            height: 4.000,
            decoration: BoxDecoration(
              color: Color(0xffc4c4c4),
              borderRadius: BorderRadius.all(Radius.circular(5)),
            ),
          ),
        ),
        Positioned(
          left: 369.0,
          width: 47.0,
          top: 787.0,
          height: 4.0,
          child: Container(
            width: 47.000,
            height: 4.000,
            decoration: BoxDecoration(
              color: Color(0xff3aa133),
              borderRadius: BorderRadius.all(Radius.circular(5)),
            ),
          ),
        ),
        Positioned(
          left: MediaQuery.of(context).size.width * 0.803,
          width: MediaQuery.of(context).size.width * 0.072,
          top: MediaQuery.of(context).size.height * 0.388,
          height: MediaQuery.of(context).size.height * 0.031,
          child: Container(
              width: MediaQuery.of(context).size.width * 0.072,
              height: MediaQuery.of(context).size.height * 0.031,
              child: AutoSizeText(
                'Skip',
                style: TextStyle(
                  fontFamily: 'Poppins',
                  fontSize: 13,
                  fontWeight: FontWeight.w300,
                  fontStyle: FontStyle.italic,
                  letterSpacing: 0,
                  color: Colors.white,
                ),
                textAlign: TextAlign.left,
              )),
        ),
        Positioned(
          left: MediaQuery.of(context).size.width * 0.736,
          width: MediaQuery.of(context).size.width * 1.128,
          top: MediaQuery.of(context).size.height * 0.448,
          height: MediaQuery.of(context).size.height * 0.419,
          child: Image.asset(
            'assets/images/481_1271.png',
            package: 'parabeac',
            width: MediaQuery.of(context).size.width * 1.128,
            height: MediaQuery.of(context).size.height * 0.419,
            fit: BoxFit.fill,
          ),
        ),
        Positioned(
          left: MediaQuery.of(context).size.width * 0.797,
          width: 0,
          top: MediaQuery.of(context).size.height * 0.752,
          height: 0,
          child: Image.asset(
            'assets/images/481_1272.png',
            package: 'parabeac',
            width: MediaQuery.of(context).size.width * 0.000,
            height: MediaQuery.of(context).size.height * 0.000,
            fit: BoxFit.fill,
          ),
        ),
        Positioned(
          left: MediaQuery.of(context).size.width * 0.974,
          width: MediaQuery.of(context).size.width * 0.01,
          top: MediaQuery.of(context).size.height * 0.788,
          height: MediaQuery.of(context).size.height * 0.002,
          child: Image.asset(
            'assets/images/481_1273.png',
            package: 'parabeac',
            width: MediaQuery.of(context).size.width * 0.010,
            height: MediaQuery.of(context).size.height * 0.002,
            fit: BoxFit.fill,
          ),
        ),
        Positioned(
          left: MediaQuery.of(context).size.width * 1.336,
          width: MediaQuery.of(context).size.width * 0.025,
          top: MediaQuery.of(context).size.height * 0.483,
          height: MediaQuery.of(context).size.height * 0.035,
          child: Image.asset(
            'assets/images/481_1274.png',
            package: 'parabeac',
            width: MediaQuery.of(context).size.width * 0.025,
            height: MediaQuery.of(context).size.height * 0.035,
            fit: BoxFit.fill,
          ),
        ),
        Positioned(
          left: MediaQuery.of(context).size.width * 1.193,
          width: MediaQuery.of(context).size.width * 0.209,
          top: MediaQuery.of(context).size.height * 0.515,
          height: MediaQuery.of(context).size.height * 0.349,
          child: Image.asset(
            'assets/images/481_1275.png',
            package: 'parabeac',
            width: MediaQuery.of(context).size.width * 0.209,
            height: MediaQuery.of(context).size.height * 0.349,
            fit: BoxFit.fill,
          ),
        ),
        Positioned(
          left: MediaQuery.of(context).size.width * 1.403,
          width: MediaQuery.of(context).size.width * 0.084,
          top: MediaQuery.of(context).size.height * 0.515,
          height: MediaQuery.of(context).size.height * 0.352,
          child: Image.asset(
            'assets/images/481_1276.png',
            package: 'parabeac',
            width: MediaQuery.of(context).size.width * 0.084,
            height: MediaQuery.of(context).size.height * 0.352,
            fit: BoxFit.fill,
          ),
        ),
        Positioned(
          left: MediaQuery.of(context).size.width * 1.231,
          width: MediaQuery.of(context).size.width * 0.032,
          top: MediaQuery.of(context).size.height * 0.55,
          height: MediaQuery.of(context).size.height * 0.018,
          child: Image.asset(
            'assets/images/481_1277.png',
            package: 'parabeac',
            width: MediaQuery.of(context).size.width * 0.032,
            height: MediaQuery.of(context).size.height * 0.018,
            fit: BoxFit.fill,
          ),
        ),
        Positioned(
          left: MediaQuery.of(context).size.width * 1.282,
          width: MediaQuery.of(context).size.width * 0.032,
          top: MediaQuery.of(context).size.height * 0.55,
          height: MediaQuery.of(context).size.height * 0.018,
          child: Image.asset(
            'assets/images/481_1278.png',
            package: 'parabeac',
            width: MediaQuery.of(context).size.width * 0.032,
            height: MediaQuery.of(context).size.height * 0.018,
            fit: BoxFit.fill,
          ),
        ),
        Positioned(
          left: MediaQuery.of(context).size.width * 1.333,
          width: MediaQuery.of(context).size.width * 0.032,
          top: MediaQuery.of(context).size.height * 0.55,
          height: MediaQuery.of(context).size.height * 0.018,
          child: Image.asset(
            'assets/images/481_1279.png',
            package: 'parabeac',
            width: MediaQuery.of(context).size.width * 0.032,
            height: MediaQuery.of(context).size.height * 0.018,
            fit: BoxFit.fill,
          ),
        ),
        Positioned(
          left: MediaQuery.of(context).size.width * 1.232,
          width: MediaQuery.of(context).size.width * 0.032,
          top: MediaQuery.of(context).size.height * 0.59,
          height: MediaQuery.of(context).size.height * 0.018,
          child: Image.asset(
            'assets/images/481_1280.png',
            package: 'parabeac',
            width: MediaQuery.of(context).size.width * 0.032,
            height: MediaQuery.of(context).size.height * 0.018,
            fit: BoxFit.fill,
          ),
        ),
        Positioned(
          left: MediaQuery.of(context).size.width * 1.283,
          width: MediaQuery.of(context).size.width * 0.032,
          top: MediaQuery.of(context).size.height * 0.59,
          height: MediaQuery.of(context).size.height * 0.018,
          child: Image.asset(
            'assets/images/481_1281.png',
            package: 'parabeac',
            width: MediaQuery.of(context).size.width * 0.032,
            height: MediaQuery.of(context).size.height * 0.018,
            fit: BoxFit.fill,
          ),
        ),
        Positioned(
          left: MediaQuery.of(context).size.width * 1.334,
          width: MediaQuery.of(context).size.width * 0.032,
          top: MediaQuery.of(context).size.height * 0.59,
          height: MediaQuery.of(context).size.height * 0.018,
          child: Image.asset(
            'assets/images/481_1282.png',
            package: 'parabeac',
            width: MediaQuery.of(context).size.width * 0.032,
            height: MediaQuery.of(context).size.height * 0.018,
            fit: BoxFit.fill,
          ),
        ),
        Positioned(
          left: MediaQuery.of(context).size.width * 1.233,
          width: MediaQuery.of(context).size.width * 0.032,
          top: MediaQuery.of(context).size.height * 0.631,
          height: MediaQuery.of(context).size.height * 0.018,
          child: Image.asset(
            'assets/images/481_1283.png',
            package: 'parabeac',
            width: MediaQuery.of(context).size.width * 0.032,
            height: MediaQuery.of(context).size.height * 0.018,
            fit: BoxFit.fill,
          ),
        ),
        Positioned(
          left: MediaQuery.of(context).size.width * 1.284,
          width: MediaQuery.of(context).size.width * 0.032,
          top: MediaQuery.of(context).size.height * 0.631,
          height: MediaQuery.of(context).size.height * 0.018,
          child: Image.asset(
            'assets/images/481_1284.png',
            package: 'parabeac',
            width: MediaQuery.of(context).size.width * 0.032,
            height: MediaQuery.of(context).size.height * 0.018,
            fit: BoxFit.fill,
          ),
        ),
        Positioned(
          left: MediaQuery.of(context).size.width * 1.335,
          width: MediaQuery.of(context).size.width * 0.032,
          top: MediaQuery.of(context).size.height * 0.631,
          height: MediaQuery.of(context).size.height * 0.018,
          child: Image.asset(
            'assets/images/481_1285.png',
            package: 'parabeac',
            width: MediaQuery.of(context).size.width * 0.032,
            height: MediaQuery.of(context).size.height * 0.018,
            fit: BoxFit.fill,
          ),
        ),
        Positioned(
          left: MediaQuery.of(context).size.width * 1.234,
          width: MediaQuery.of(context).size.width * 0.032,
          top: MediaQuery.of(context).size.height * 0.672,
          height: MediaQuery.of(context).size.height * 0.018,
          child: Image.asset(
            'assets/images/481_1286.png',
            package: 'parabeac',
            width: MediaQuery.of(context).size.width * 0.032,
            height: MediaQuery.of(context).size.height * 0.018,
            fit: BoxFit.fill,
          ),
        ),
        Positioned(
          left: MediaQuery.of(context).size.width * 1.285,
          width: MediaQuery.of(context).size.width * 0.032,
          top: MediaQuery.of(context).size.height * 0.672,
          height: MediaQuery.of(context).size.height * 0.018,
          child: Image.asset(
            'assets/images/481_1287.png',
            package: 'parabeac',
            width: MediaQuery.of(context).size.width * 0.032,
            height: MediaQuery.of(context).size.height * 0.018,
            fit: BoxFit.fill,
          ),
        ),
        Positioned(
          left: MediaQuery.of(context).size.width * 1.336,
          width: MediaQuery.of(context).size.width * 0.032,
          top: MediaQuery.of(context).size.height * 0.672,
          height: MediaQuery.of(context).size.height * 0.018,
          child: Image.asset(
            'assets/images/481_1288.png',
            package: 'parabeac',
            width: MediaQuery.of(context).size.width * 0.032,
            height: MediaQuery.of(context).size.height * 0.018,
            fit: BoxFit.fill,
          ),
        ),
        Positioned(
          left: MediaQuery.of(context).size.width * 1.235,
          width: MediaQuery.of(context).size.width * 0.032,
          top: MediaQuery.of(context).size.height * 0.712,
          height: MediaQuery.of(context).size.height * 0.018,
          child: Image.asset(
            'assets/images/481_1289.png',
            package: 'parabeac',
            width: MediaQuery.of(context).size.width * 0.032,
            height: MediaQuery.of(context).size.height * 0.018,
            fit: BoxFit.fill,
          ),
        ),
        Positioned(
          left: MediaQuery.of(context).size.width * 1.286,
          width: MediaQuery.of(context).size.width * 0.032,
          top: MediaQuery.of(context).size.height * 0.712,
          height: MediaQuery.of(context).size.height * 0.018,
          child: Image.asset(
            'assets/images/481_1290.png',
            package: 'parabeac',
            width: MediaQuery.of(context).size.width * 0.032,
            height: MediaQuery.of(context).size.height * 0.018,
            fit: BoxFit.fill,
          ),
        ),
        Positioned(
          left: MediaQuery.of(context).size.width * 1.337,
          width: MediaQuery.of(context).size.width * 0.032,
          top: MediaQuery.of(context).size.height * 0.712,
          height: MediaQuery.of(context).size.height * 0.018,
          child: Image.asset(
            'assets/images/481_1291.png',
            package: 'parabeac',
            width: MediaQuery.of(context).size.width * 0.032,
            height: MediaQuery.of(context).size.height * 0.018,
            fit: BoxFit.fill,
          ),
        ),
        Positioned(
          left: MediaQuery.of(context).size.width * 1.236,
          width: MediaQuery.of(context).size.width * 0.032,
          top: MediaQuery.of(context).size.height * 0.753,
          height: MediaQuery.of(context).size.height * 0.018,
          child: Image.asset(
            'assets/images/481_1292.png',
            package: 'parabeac',
            width: MediaQuery.of(context).size.width * 0.032,
            height: MediaQuery.of(context).size.height * 0.018,
            fit: BoxFit.fill,
          ),
        ),
        Positioned(
          left: MediaQuery.of(context).size.width * 1.287,
          width: MediaQuery.of(context).size.width * 0.032,
          top: MediaQuery.of(context).size.height * 0.753,
          height: MediaQuery.of(context).size.height * 0.018,
          child: Image.asset(
            'assets/images/481_1293.png',
            package: 'parabeac',
            width: MediaQuery.of(context).size.width * 0.032,
            height: MediaQuery.of(context).size.height * 0.018,
            fit: BoxFit.fill,
          ),
        ),
        Positioned(
          left: MediaQuery.of(context).size.width * 1.338,
          width: MediaQuery.of(context).size.width * 0.032,
          top: MediaQuery.of(context).size.height * 0.753,
          height: MediaQuery.of(context).size.height * 0.018,
          child: Image.asset(
            'assets/images/481_1294.png',
            package: 'parabeac',
            width: MediaQuery.of(context).size.width * 0.032,
            height: MediaQuery.of(context).size.height * 0.018,
            fit: BoxFit.fill,
          ),
        ),
        Positioned(
          left: MediaQuery.of(context).size.width * 1.237,
          width: MediaQuery.of(context).size.width * 0.032,
          top: MediaQuery.of(context).size.height * 0.793,
          height: MediaQuery.of(context).size.height * 0.018,
          child: Image.asset(
            'assets/images/481_1295.png',
            package: 'parabeac',
            width: MediaQuery.of(context).size.width * 0.032,
            height: MediaQuery.of(context).size.height * 0.018,
            fit: BoxFit.fill,
          ),
        ),
        Positioned(
          left: MediaQuery.of(context).size.width * 1.288,
          width: MediaQuery.of(context).size.width * 0.032,
          top: MediaQuery.of(context).size.height * 0.793,
          height: MediaQuery.of(context).size.height * 0.018,
          child: Image.asset(
            'assets/images/481_1296.png',
            package: 'parabeac',
            width: MediaQuery.of(context).size.width * 0.032,
            height: MediaQuery.of(context).size.height * 0.018,
            fit: BoxFit.fill,
          ),
        ),
        Positioned(
          left: MediaQuery.of(context).size.width * 1.339,
          width: MediaQuery.of(context).size.width * 0.032,
          top: MediaQuery.of(context).size.height * 0.793,
          height: MediaQuery.of(context).size.height * 0.018,
          child: Image.asset(
            'assets/images/481_1297.png',
            package: 'parabeac',
            width: MediaQuery.of(context).size.width * 0.032,
            height: MediaQuery.of(context).size.height * 0.018,
            fit: BoxFit.fill,
          ),
        ),
        Positioned(
          left: MediaQuery.of(context).size.width * 1.237,
          width: MediaQuery.of(context).size.width * 0.032,
          top: MediaQuery.of(context).size.height * 0.834,
          height: MediaQuery.of(context).size.height * 0.009,
          child: Image.asset(
            'assets/images/481_1298.png',
            package: 'parabeac',
            width: MediaQuery.of(context).size.width * 0.032,
            height: MediaQuery.of(context).size.height * 0.009,
            fit: BoxFit.fill,
          ),
        ),
        Positioned(
          left: MediaQuery.of(context).size.width * 1.289,
          width: MediaQuery.of(context).size.width * 0.032,
          top: MediaQuery.of(context).size.height * 0.834,
          height: MediaQuery.of(context).size.height * 0.018,
          child: Image.asset(
            'assets/images/481_1299.png',
            package: 'parabeac',
            width: MediaQuery.of(context).size.width * 0.032,
            height: MediaQuery.of(context).size.height * 0.018,
            fit: BoxFit.fill,
          ),
        ),
        Positioned(
          left: MediaQuery.of(context).size.width * 1.34,
          width: MediaQuery.of(context).size.width * 0.032,
          top: MediaQuery.of(context).size.height * 0.834,
          height: MediaQuery.of(context).size.height * 0.018,
          child: Image.asset(
            'assets/images/481_1300.png',
            package: 'parabeac',
            width: MediaQuery.of(context).size.width * 0.032,
            height: MediaQuery.of(context).size.height * 0.018,
            fit: BoxFit.fill,
          ),
        ),
        Positioned(
          left: MediaQuery.of(context).size.width * 1.623,
          width: MediaQuery.of(context).size.width * 0.025,
          top: MediaQuery.of(context).size.height * 0.66,
          height: MediaQuery.of(context).size.height * 0.021,
          child: Image.asset(
            'assets/images/481_1301.png',
            package: 'parabeac',
            width: MediaQuery.of(context).size.width * 0.025,
            height: MediaQuery.of(context).size.height * 0.021,
            fit: BoxFit.fill,
          ),
        ),
        Positioned(
          left: MediaQuery.of(context).size.width * 1.457,
          width: MediaQuery.of(context).size.width * 0.209,
          top: MediaQuery.of(context).size.height * 0.678,
          height: MediaQuery.of(context).size.height * 0.189,
          child: Image.asset(
            'assets/images/481_1302.png',
            package: 'parabeac',
            width: MediaQuery.of(context).size.width * 0.209,
            height: MediaQuery.of(context).size.height * 0.189,
            fit: BoxFit.fill,
          ),
        ),
        Positioned(
          left: MediaQuery.of(context).size.width * 1.667,
          width: MediaQuery.of(context).size.width * 0.084,
          top: MediaQuery.of(context).size.height * 0.678,
          height: MediaQuery.of(context).size.height * 0.172,
          child: Image.asset(
            'assets/images/481_1303.png',
            package: 'parabeac',
            width: MediaQuery.of(context).size.width * 0.084,
            height: MediaQuery.of(context).size.height * 0.172,
            fit: BoxFit.fill,
          ),
        ),
        Positioned(
          left: MediaQuery.of(context).size.width * 1.499,
          width: MediaQuery.of(context).size.width * 0.032,
          top: MediaQuery.of(context).size.height * 0.712,
          height: MediaQuery.of(context).size.height * 0.018,
          child: Image.asset(
            'assets/images/481_1304.png',
            package: 'parabeac',
            width: MediaQuery.of(context).size.width * 0.032,
            height: MediaQuery.of(context).size.height * 0.018,
            fit: BoxFit.fill,
          ),
        ),
        Positioned(
          left: MediaQuery.of(context).size.width * 1.55,
          width: MediaQuery.of(context).size.width * 0.032,
          top: MediaQuery.of(context).size.height * 0.712,
          height: MediaQuery.of(context).size.height * 0.018,
          child: Image.asset(
            'assets/images/481_1305.png',
            package: 'parabeac',
            width: MediaQuery.of(context).size.width * 0.032,
            height: MediaQuery.of(context).size.height * 0.018,
            fit: BoxFit.fill,
          ),
        ),
        Positioned(
          left: MediaQuery.of(context).size.width * 1.601,
          width: MediaQuery.of(context).size.width * 0.032,
          top: MediaQuery.of(context).size.height * 0.712,
          height: MediaQuery.of(context).size.height * 0.018,
          child: Image.asset(
            'assets/images/481_1306.png',
            package: 'parabeac',
            width: MediaQuery.of(context).size.width * 0.032,
            height: MediaQuery.of(context).size.height * 0.018,
            fit: BoxFit.fill,
          ),
        ),
        Positioned(
          left: MediaQuery.of(context).size.width * 1.5,
          width: MediaQuery.of(context).size.width * 0.032,
          top: MediaQuery.of(context).size.height * 0.753,
          height: MediaQuery.of(context).size.height * 0.018,
          child: Image.asset(
            'assets/images/481_1307.png',
            package: 'parabeac',
            width: MediaQuery.of(context).size.width * 0.032,
            height: MediaQuery.of(context).size.height * 0.018,
            fit: BoxFit.fill,
          ),
        ),
        Positioned(
          left: MediaQuery.of(context).size.width * 1.551,
          width: MediaQuery.of(context).size.width * 0.032,
          top: MediaQuery.of(context).size.height * 0.753,
          height: MediaQuery.of(context).size.height * 0.018,
          child: Image.asset(
            'assets/images/481_1308.png',
            package: 'parabeac',
            width: MediaQuery.of(context).size.width * 0.032,
            height: MediaQuery.of(context).size.height * 0.018,
            fit: BoxFit.fill,
          ),
        ),
        Positioned(
          left: MediaQuery.of(context).size.width * 1.602,
          width: MediaQuery.of(context).size.width * 0.032,
          top: MediaQuery.of(context).size.height * 0.753,
          height: MediaQuery.of(context).size.height * 0.018,
          child: Image.asset(
            'assets/images/481_1309.png',
            package: 'parabeac',
            width: MediaQuery.of(context).size.width * 0.032,
            height: MediaQuery.of(context).size.height * 0.018,
            fit: BoxFit.fill,
          ),
        ),
        Positioned(
          left: MediaQuery.of(context).size.width * 1.501,
          width: MediaQuery.of(context).size.width * 0.032,
          top: MediaQuery.of(context).size.height * 0.793,
          height: MediaQuery.of(context).size.height * 0.018,
          child: Image.asset(
            'assets/images/481_1310.png',
            package: 'parabeac',
            width: MediaQuery.of(context).size.width * 0.032,
            height: MediaQuery.of(context).size.height * 0.018,
            fit: BoxFit.fill,
          ),
        ),
        Positioned(
          left: MediaQuery.of(context).size.width * 1.552,
          width: MediaQuery.of(context).size.width * 0.032,
          top: MediaQuery.of(context).size.height * 0.793,
          height: MediaQuery.of(context).size.height * 0.018,
          child: Image.asset(
            'assets/images/481_1311.png',
            package: 'parabeac',
            width: MediaQuery.of(context).size.width * 0.032,
            height: MediaQuery.of(context).size.height * 0.018,
            fit: BoxFit.fill,
          ),
        ),
        Positioned(
          left: MediaQuery.of(context).size.width * 1.603,
          width: MediaQuery.of(context).size.width * 0.032,
          top: MediaQuery.of(context).size.height * 0.793,
          height: MediaQuery.of(context).size.height * 0.018,
          child: Image.asset(
            'assets/images/481_1312.png',
            package: 'parabeac',
            width: MediaQuery.of(context).size.width * 0.032,
            height: MediaQuery.of(context).size.height * 0.018,
            fit: BoxFit.fill,
          ),
        ),
        Positioned(
          left: MediaQuery.of(context).size.width * 1.501,
          width: MediaQuery.of(context).size.width * 0.032,
          top: MediaQuery.of(context).size.height * 0.834,
          height: MediaQuery.of(context).size.height * 0.018,
          child: Image.asset(
            'assets/images/481_1313.png',
            package: 'parabeac',
            width: MediaQuery.of(context).size.width * 0.032,
            height: MediaQuery.of(context).size.height * 0.018,
            fit: BoxFit.fill,
          ),
        ),
        Positioned(
          left: MediaQuery.of(context).size.width * 1.553,
          width: MediaQuery.of(context).size.width * 0.032,
          top: MediaQuery.of(context).size.height * 0.834,
          height: MediaQuery.of(context).size.height * 0.018,
          child: Image.asset(
            'assets/images/481_1314.png',
            package: 'parabeac',
            width: MediaQuery.of(context).size.width * 0.032,
            height: MediaQuery.of(context).size.height * 0.018,
            fit: BoxFit.fill,
          ),
        ),
        Positioned(
          left: MediaQuery.of(context).size.width * 1.604,
          width: MediaQuery.of(context).size.width * 0.032,
          top: MediaQuery.of(context).size.height * 0.834,
          height: MediaQuery.of(context).size.height * 0.018,
          child: Image.asset(
            'assets/images/481_1315.png',
            package: 'parabeac',
            width: MediaQuery.of(context).size.width * 0.032,
            height: MediaQuery.of(context).size.height * 0.018,
            fit: BoxFit.fill,
          ),
        ),
        Positioned(
          left: MediaQuery.of(context).size.width * 1.482,
          width: MediaQuery.of(context).size.width * 0.126,
          top: MediaQuery.of(context).size.height * 0.873,
          height: MediaQuery.of(context).size.height * 0.022,
          child: Image.asset(
            'assets/images/481_1316.png',
            package: 'parabeac',
            width: MediaQuery.of(context).size.width * 0.126,
            height: MediaQuery.of(context).size.height * 0.022,
            fit: BoxFit.fill,
          ),
        ),
        Positioned(
          left: MediaQuery.of(context).size.width * 0.818,
          width: MediaQuery.of(context).size.width * 0.466,
          top: MediaQuery.of(context).size.height * 0.774,
          height: MediaQuery.of(context).size.height * 0.114,
          child: Image.asset(
            'assets/images/481_1317.png',
            package: 'parabeac',
            width: MediaQuery.of(context).size.width * 0.466,
            height: MediaQuery.of(context).size.height * 0.114,
            fit: BoxFit.fill,
          ),
        ),
        Positioned(
          left: MediaQuery.of(context).size.width * 0.821,
          width: MediaQuery.of(context).size.width * 0.098,
          top: MediaQuery.of(context).size.height * 0.794,
          height: MediaQuery.of(context).size.height * 0.082,
          child: Image.asset(
            'assets/images/481_1318.png',
            package: 'parabeac',
            width: MediaQuery.of(context).size.width * 0.098,
            height: MediaQuery.of(context).size.height * 0.082,
            fit: BoxFit.fill,
          ),
        ),
        Positioned(
          left: MediaQuery.of(context).size.width * 1.148,
          width: MediaQuery.of(context).size.width * 0.141,
          top: MediaQuery.of(context).size.height * 0.81,
          height: MediaQuery.of(context).size.height * 0.102,
          child: Image.asset(
            'assets/images/481_1319.png',
            package: 'parabeac',
            width: MediaQuery.of(context).size.width * 0.141,
            height: MediaQuery.of(context).size.height * 0.102,
            fit: BoxFit.fill,
          ),
        ),
        Positioned(
          left: MediaQuery.of(context).size.width * 0.818,
          width: MediaQuery.of(context).size.width * 0.82,
          top: MediaQuery.of(context).size.height * 0.766,
          height: MediaQuery.of(context).size.height * 0.124,
          child: Image.asset(
            'assets/images/481_1320.png',
            package: 'parabeac',
            width: MediaQuery.of(context).size.width * 0.820,
            height: MediaQuery.of(context).size.height * 0.124,
            fit: BoxFit.fill,
          ),
        ),
        Positioned(
          left: MediaQuery.of(context).size.width * 0.865,
          width: MediaQuery.of(context).size.width * 0.574,
          top: MediaQuery.of(context).size.height * 0.695,
          height: MediaQuery.of(context).size.height * 0.066,
          child: Image.asset(
            'assets/images/481_1321.png',
            package: 'parabeac',
            width: MediaQuery.of(context).size.width * 0.574,
            height: MediaQuery.of(context).size.height * 0.066,
            fit: BoxFit.fill,
          ),
        ),
        Positioned(
          left: MediaQuery.of(context).size.width * 0.825,
          width: MediaQuery.of(context).size.width * 0.816,
          top: MediaQuery.of(context).size.height * 0.742,
          height: MediaQuery.of(context).size.height * 0.137,
          child: Image.asset(
            'assets/images/481_1322.png',
            package: 'parabeac',
            width: MediaQuery.of(context).size.width * 0.816,
            height: MediaQuery.of(context).size.height * 0.137,
            fit: BoxFit.fill,
          ),
        ),
        Positioned(
          left: MediaQuery.of(context).size.width * 0.939,
          width: MediaQuery.of(context).size.width * 0.035,
          top: MediaQuery.of(context).size.height * 0.765,
          height: MediaQuery.of(context).size.height * 0.006,
          child: Image.asset(
            'assets/images/481_1323.png',
            package: 'parabeac',
            width: MediaQuery.of(context).size.width * 0.035,
            height: MediaQuery.of(context).size.height * 0.006,
            fit: BoxFit.fill,
          ),
        ),
        Positioned(
          left: MediaQuery.of(context).size.width * 1.33,
          width: MediaQuery.of(context).size.width * 0.032,
          top: MediaQuery.of(context).size.height * 0.842,
          height: MediaQuery.of(context).size.height * 0.018,
          child: Image.asset(
            'assets/images/481_1324.png',
            package: 'parabeac',
            width: MediaQuery.of(context).size.width * 0.032,
            height: MediaQuery.of(context).size.height * 0.018,
            fit: BoxFit.fill,
          ),
        ),
        Positioned(
          left: MediaQuery.of(context).size.width * 1.279,
          width: MediaQuery.of(context).size.width * 0.083,
          top: MediaQuery.of(context).size.height * 0.765,
          height: MediaQuery.of(context).size.height * 0.042,
          child: Image.asset(
            'assets/images/481_1325.png',
            package: 'parabeac',
            width: MediaQuery.of(context).size.width * 0.083,
            height: MediaQuery.of(context).size.height * 0.042,
            fit: BoxFit.fill,
          ),
        ),
        Positioned(
          left: MediaQuery.of(context).size.width * 1.562,
          width: MediaQuery.of(context).size.width * 0.068,
          top: MediaQuery.of(context).size.height * 0.76,
          height: MediaQuery.of(context).size.height * 0.036,
          child: Image.asset(
            'assets/images/481_1326.png',
            package: 'parabeac',
            width: MediaQuery.of(context).size.width * 0.068,
            height: MediaQuery.of(context).size.height * 0.036,
            fit: BoxFit.fill,
          ),
        ),
        Positioned(
          left: MediaQuery.of(context).size.width * 0.887,
          width: MediaQuery.of(context).size.width * 0.08,
          top: MediaQuery.of(context).size.height * 0.705,
          height: MediaQuery.of(context).size.height * 0.037,
          child: Image.asset(
            'assets/images/481_1327.png',
            package: 'parabeac',
            width: MediaQuery.of(context).size.width * 0.080,
            height: MediaQuery.of(context).size.height * 0.037,
            fit: BoxFit.fill,
          ),
        ),
        Positioned(
          left: MediaQuery.of(context).size.width * 0.978,
          width: MediaQuery.of(context).size.width * 0.124,
          top: MediaQuery.of(context).size.height * 0.697,
          height: MediaQuery.of(context).size.height * 0.051,
          child: Image.asset(
            'assets/images/481_1328.png',
            package: 'parabeac',
            width: MediaQuery.of(context).size.width * 0.124,
            height: MediaQuery.of(context).size.height * 0.051,
            fit: BoxFit.fill,
          ),
        ),
        Positioned(
          left: MediaQuery.of(context).size.width * 1.128,
          width: MediaQuery.of(context).size.width * 0.276,
          top: MediaQuery.of(context).size.height * 0.698,
          height: MediaQuery.of(context).size.height * 0.052,
          child: Image.asset(
            'assets/images/481_1329.png',
            package: 'parabeac',
            width: MediaQuery.of(context).size.width * 0.276,
            height: MediaQuery.of(context).size.height * 0.052,
            fit: BoxFit.fill,
          ),
        ),
        Positioned(
          left: MediaQuery.of(context).size.width * 0.914,
          width: MediaQuery.of(context).size.width * 0.421,
          top: MediaQuery.of(context).size.height * 0.683,
          height: MediaQuery.of(context).size.height * 0.02,
          child: Image.asset(
            'assets/images/481_1330.png',
            package: 'parabeac',
            width: MediaQuery.of(context).size.width * 0.421,
            height: MediaQuery.of(context).size.height * 0.020,
            fit: BoxFit.fill,
          ),
        ),
        Positioned(
          left: MediaQuery.of(context).size.width * 0.828,
          width: MediaQuery.of(context).size.width * 0.05,
          top: MediaQuery.of(context).size.height * 0.808,
          height: MediaQuery.of(context).size.height * 0.057,
          child: Image.asset(
            'assets/images/481_1331.png',
            package: 'parabeac',
            width: MediaQuery.of(context).size.width * 0.050,
            height: MediaQuery.of(context).size.height * 0.057,
            fit: BoxFit.fill,
          ),
        ),
        Positioned(
          left: MediaQuery.of(context).size.width * 1.159,
          width: MediaQuery.of(context).size.width * 0.079,
          top: MediaQuery.of(context).size.height * 0.827,
          height: MediaQuery.of(context).size.height * 0.073,
          child: Image.asset(
            'assets/images/481_1332.png',
            package: 'parabeac',
            width: MediaQuery.of(context).size.width * 0.079,
            height: MediaQuery.of(context).size.height * 0.073,
            fit: BoxFit.fill,
          ),
        ),
        Positioned(
          left: MediaQuery.of(context).size.width * 1.061,
          width: MediaQuery.of(context).size.width * 0.033,
          top: MediaQuery.of(context).size.height * 0.747,
          height: MediaQuery.of(context).size.height * 0.019,
          child: Image.asset(
            'assets/images/481_1333.png',
            package: 'parabeac',
            width: MediaQuery.of(context).size.width * 0.033,
            height: MediaQuery.of(context).size.height * 0.019,
            fit: BoxFit.fill,
          ),
        ),
        Positioned(
          left: MediaQuery.of(context).size.width * 1.021,
          width: MediaQuery.of(context).size.width * 0.057,
          top: MediaQuery.of(context).size.height * 0.735,
          height: MediaQuery.of(context).size.height * 0.021,
          child: Image.asset(
            'assets/images/481_1334.png',
            package: 'parabeac',
            width: MediaQuery.of(context).size.width * 0.057,
            height: MediaQuery.of(context).size.height * 0.021,
            fit: BoxFit.fill,
          ),
        ),
        Positioned(
          left: MediaQuery.of(context).size.width * 1.395,
          width: MediaQuery.of(context).size.width * 0.239,
          top: MediaQuery.of(context).size.height * 0.794,
          height: MediaQuery.of(context).size.height * 0.038,
          child: Image.asset(
            'assets/images/481_1335.png',
            package: 'parabeac',
            width: MediaQuery.of(context).size.width * 0.239,
            height: MediaQuery.of(context).size.height * 0.038,
            fit: BoxFit.fill,
          ),
        ),
        Positioned(
          left: MediaQuery.of(context).size.width * 1.42,
          width: MediaQuery.of(context).size.width * 0.191,
          top: MediaQuery.of(context).size.height * 0.799,
          height: MediaQuery.of(context).size.height * 0.005,
          child: Image.asset(
            'assets/images/481_1336.png',
            package: 'parabeac',
            width: MediaQuery.of(context).size.width * 0.191,
            height: MediaQuery.of(context).size.height * 0.005,
            fit: BoxFit.fill,
          ),
        ),
        Positioned(
          left: MediaQuery.of(context).size.width * 1.41,
          width: MediaQuery.of(context).size.width * 0.208,
          top: MediaQuery.of(context).size.height * 0.803,
          height: MediaQuery.of(context).size.height * 0.007,
          child: Image.asset(
            'assets/images/481_1337.png',
            package: 'parabeac',
            width: MediaQuery.of(context).size.width * 0.208,
            height: MediaQuery.of(context).size.height * 0.007,
            fit: BoxFit.fill,
          ),
        ),
        Positioned(
          left: MediaQuery.of(context).size.width * 1.403,
          width: MediaQuery.of(context).size.width * 0.223,
          top: MediaQuery.of(context).size.height * 0.808,
          height: MediaQuery.of(context).size.height * 0.008,
          child: Image.asset(
            'assets/images/481_1338.png',
            package: 'parabeac',
            width: MediaQuery.of(context).size.width * 0.223,
            height: MediaQuery.of(context).size.height * 0.008,
            fit: BoxFit.fill,
          ),
        ),
        Positioned(
          left: MediaQuery.of(context).size.width * 0.731,
          width: MediaQuery.of(context).size.width * 0.259,
          top: MediaQuery.of(context).size.height * 0.654,
          height: MediaQuery.of(context).size.height * 0.237,
          child: Image.asset(
            'assets/images/481_1339.png',
            package: 'parabeac',
            width: MediaQuery.of(context).size.width * 0.259,
            height: MediaQuery.of(context).size.height * 0.237,
            fit: BoxFit.fill,
          ),
        ),
      ]),
    );
  }

  @override
  void dispose() {
    super.dispose();
  }
}
